const API_BASE=(import.meta?.env?.VITE_API_BASE_URL||'http://localhost:50448/api').replace(/\/$/,'');
export const API_URL=API_BASE;
export const CUSTOMER_URL=import.meta?.env?.VITE_CUSTOMER_URL||'http://localhost:5173';
const readToken=()=>localStorage.getItem('ha_token');
export const currentUser=()=>{try{return JSON.parse(localStorage.getItem('ha_current_user')||'null')}catch{return null}};
const storeUser=u=>localStorage.setItem('ha_current_user',JSON.stringify(u));
export const money=n=>new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:2}).format(Number(n||0));
export async function api(path,options={}){const isFormData=typeof FormData!=='undefined'&&options.body instanceof FormData;
const headers={...(isFormData?{}:{'Content-Type':'application/json'}),...(options.headers||{})};const t=readToken();if(t)headers.Authorization=`Bearer ${t}`;const res=await fetch(`${API_BASE}${path}`,{...options,headers});const raw=await res.text();let body=null;try{body=raw?JSON.parse(raw):null}catch{body=raw}if(res.status===401){localStorage.removeItem('ha_token');localStorage.removeItem('ha_current_user')}if(!res.ok)throw new Error(body?.message||body?.title||body||`Request failed: ${res.status}`);return body;}
export const auth={async login(data){const x=await api('/auth/login',{method:'POST',body:JSON.stringify(data)});localStorage.setItem('ha_token',x.accessToken);storeUser(x.user);return x;},async register(data){const x=await api('/auth/register',{method:'POST',body:JSON.stringify(data)});localStorage.setItem('ha_token',x.accessToken);storeUser(x.user);return x;},logout(){localStorage.removeItem('ha_token');localStorage.removeItem('ha_current_user')},me(){return currentUser()}};
export const outlets={list:()=>api('/marketplace/outlets'),get:slug=>api(`/marketplace/outlets/${encodeURIComponent(slug)}`),availability:(lat,lng)=>api(`/marketplace/availability?latitude=${lat}&longitude=${lng}`)};
export const locations={areas:city=>api(`/marketplace/city-areas${city?`?city=${encodeURIComponent(city)}`:''}`)};
export const catalog={ingredients:()=>api('/catalog/ingredients'),allergens:()=>api('/catalog/allergens')};
export const recipes={list:(outletId,category)=>api(`/marketplace/outlets/${outletId}/recipes${category?`?category=${encodeURIComponent(category)}`:''}`),forOutlet:category=>api(`/outlets/me/recipes${category?`?category=${encodeURIComponent(category)}`:''}`),create:data=>api('/outlets/me/recipes',{method:'POST',body:JSON.stringify(data)}),update:(id,data)=>api(`/outlets/me/recipes/${id}`,{method:'PUT',body:JSON.stringify(data)}),remove:id=>api(`/outlets/me/recipes/${id}`,{method:'DELETE'})};
export const menu={outlet:id=>api(`/marketplace/outlets/${id}/menu`),mine:()=>api('/outlets/me/menu'),save:items=>api('/outlets/me/menu',{method:'PUT',body:JSON.stringify({items})})};
export const customer={profile:()=>api('/customer/profile/preferences'),saveProfile:data=>api('/customer/profile/preferences',{method:'PUT',body:JSON.stringify(data)}),addresses:()=>api('/customer/addresses'),createAddress:data=>api('/customer/addresses',{method:'POST',body:JSON.stringify(data)}),updateAddress:(id,data)=>api(`/customer/addresses/${id}`,{method:'PUT',body:JSON.stringify(data)}),deleteAddress:id=>api(`/customer/addresses/${id}`,{method:'DELETE'}),deliveryQuotes:outletId=>api(`/customer/outlets/${outletId}/delivery-quotes`),subscriptions:()=>api('/customer/subscriptions'),orders:()=>api('/customer/orders'),quote:data=>api('/customer/subscriptions/quote',{method:'POST',body:JSON.stringify(data)}),subscribe:data=>api('/customer/subscriptions',{method:'POST',body:JSON.stringify(data)}),recipes:(id,category)=>api(`/customer/subscriptions/${id}/recipes${category?`?category=${encodeURIComponent(category)}`:''}`),menu:id=>api(`/customer/subscriptions/${id}/menu`),mealSelections:(id,weekStart)=>api(`/customer/subscriptions/${id}/meal-selections${weekStart?`?weekStart=${encodeURIComponent(weekStart)}`:''}`),saveSelections:(id,data)=>api(`/customer/subscriptions/${id}/meal-selections`,{method:'PUT',body:JSON.stringify(data)}),skipMeal:(sid,mid,reason)=>api(`/customer/subscriptions/${sid}/meal-selections/${mid}/skip`,{method:'POST',body:JSON.stringify({reason})}),skipDay:(sid,date,reason)=>api(`/customer/subscriptions/${sid}/days/${encodeURIComponent(date)}/skip`,{method:'POST',body:JSON.stringify({reason})}),rescheduleMeal:(sid,mid,data)=>api(`/customer/subscriptions/${sid}/meal-selections/${mid}/reschedule`,{method:'POST',body:JSON.stringify(data)}),credit:()=>api('/customer/credit'),creditTransactions:()=>api('/customer/credit/transactions'),pay:(subscriptionId,idempotencyKey,provider='Mock')=>api('/customer/payments',{method:'POST',body:JSON.stringify({subscriptionId,idempotencyKey,provider})})};
export const outletAdmin={outlet:()=>api('/outlets/me'),dashboard:()=>api('/outlets/me/dashboard'),subscriptionDetail:id=>api(`/outlets/me/subscriptions/${id}`),kitchen:date=>api(`/outlets/me/kitchen${date?`?date=${encodeURIComponent(date)}`:''}`),billing:()=>api('/outlets/me/billing'),subscriptionPlans:()=>api('/outlets/me/subscription/plans'),changeSubscription:(saasPlanId,billingCycle)=>api('/outlets/me/subscription',{method:'PUT',body:JSON.stringify({saasPlanId,billingCycle})}),customers:()=>api('/outlets/me/customers'),subscriptions:()=>api('/outlets/me/subscriptions'),orders:()=>api('/outlets/me/orders'),deliveries:()=>api('/outlets/me/deliveries'),menu:()=>api('/outlets/me/menu'),saveMenu:items=>api('/outlets/me/menu',{method:'PUT',body:JSON.stringify({items})}),recipes:()=>recipes.forOutlet(),createRecipe:data=>recipes.create(data),updateRecipe:(id,data)=>recipes.update(id,data),deleteRecipe:id=>recipes.remove(id),uploadRecipeImage:file=>{const form=new FormData();form.append('file',file);return api('/outlets/me/recipes/image',{method:'POST',body:form});},pricingRules:()=>api('/outlets/me/delivery-pricing'),addPricingRule:data=>api('/outlets/me/delivery-pricing',{method:'POST',body:JSON.stringify(data)}),deletePricingRule:id=>api(`/outlets/me/delivery-pricing/${id}`,{method:'DELETE'}),availableDeliveryAreas:city=>api(`/outlets/me/delivery-areas/available${city?`?city=${encodeURIComponent(city)}`:''}`),selectedDeliveryAreas:()=>api('/outlets/me/delivery-areas'),saveDeliveryAreas:cityAreaIds=>api('/outlets/me/delivery-areas',{method:'PUT',body:JSON.stringify({cityAreaIds})}),discountTiers:()=>api('/outlets/me/discount-tiers'),addDiscountTier:data=>api('/outlets/me/discount-tiers',{method:'POST',body:JSON.stringify(data)}),updateDiscountTier:(id,data)=>api(`/outlets/me/discount-tiers/${id}`,{method:'PUT',body:JSON.stringify(data)}),deleteDiscountTier:id=>api(`/outlets/me/discount-tiers/${id}`,{method:'DELETE'})};
export const admin={outlets:()=>api('/admin/outlets'),users:()=>api('/admin/users'),dashboard:()=>api('/admin/dashboard'),revenue:()=>api('/admin/reports/revenue'),cityAreas:city=>api(`/admin/city-areas${city?`?city=${encodeURIComponent(city)}`:''}`),createCityArea:data=>api('/admin/city-areas',{method:'POST',body:JSON.stringify(data)})};
export function distanceKm(lat1,lon1,lat2,lon2){const R=6371,dLat=(lat2-lat1)*Math.PI/180,dLon=(lon2-lon1)*Math.PI/180,a=Math.sin(dLat/2)**2+Math.cos(lat1*Math.PI/180)*Math.cos(lat2*Math.PI/180)*Math.sin(dLon/2)**2;return R*2*Math.atan2(Math.sqrt(a),Math.sqrt(1-a));}
