import React,{useMemo,useState}from'react';
const DEFAULT_SLOTS=[{id:1,label:'Morning',icon:'☀️'},{id:2,label:'Afternoon',icon:'🥗'},{id:3,label:'Evening',icon:'🍲'},{id:4,label:'Night',icon:'🌙'}];
const normalize=v=>Array.isArray(v)?v.filter(Boolean):(v?[v]:[]);
const groupName=x=>String(x?.optionGroup||x?.mealType||'Meal').trim()||'Meal';
export default function PackageBuilder({days=[],menuFor,selections={},getSelected,onSelectionChange,addresses=[],deliveryMode='OneDeliveryPerDay',getDayAddress=()=>'',onDayAddressChange=()=>{},getItemAddress=()=>'',onItemAddressChange=()=>{},getPortion=()=>1,onPortionChange=()=>{},showAddresses=false,showPortion=true,showPrice=true,money=x=>String(x??''),slotConfig=DEFAULT_SLOTS,compact=false,emptyMessage='No menu configured for this slot.',disabledDays=[],onAddAddress,canSelect,onBlockedSelect,showLargePortion,title='Build your meals, your way.',subtitle='Choose from every configured group. Your selections update instantly.'}){
 const[activeFilter,setActiveFilter]=useState({});
 const daysByWeek=useMemo(()=>days.reduce((a,d)=>{const w=d.week||1;(a[w]??=[]).push(d);return a},{}),[days]);
 const toggle=(date,slot,item)=>{if(canSelect&&!canSelect(item,date,slot)){onBlockedSelect?.(item,date,slot);return;}const current=normalize(getSelected(date,slot)),options=menuFor(date,slot)||[],group=groupName(item),groupItems=options.filter(x=>groupName(x)===group),max=Math.max(1,Number(item.maxSelections||groupItems[0]?.maxSelections||1)),exists=current.some(x=>x.recipeId===item.recipeId),same=current.filter(x=>groupItems.some(g=>g.recipeId===x.recipeId));let next;if(exists)next=current.filter(x=>x.recipeId!==item.recipeId);else if(same.length>=max)next=[...current.filter(x=>!groupItems.some(g=>g.recipeId===x.recipeId)),...same.slice(1-max),{recipeId:item.recipeId,portion:1}];else next=[...current,{recipeId:item.recipeId,portion:1}];onSelectionChange(date,slot,next)};
 return <section className={'sharedPackageBuilder '+(compact?'compact':'')}><div className='sharedPackageHero'><div><span className='sharedPackageEyebrow'>MEAL PACKAGE BUILDER</span><h2>{title}</h2><p>{subtitle}</p></div><div className='sharedPackagePulse'><b>{Object.values(selections||{}).flatMap(normalize).length}</b><span>items selected</span></div></div>
 {Object.entries(daysByWeek).map(([week,weekDays])=><div className='sharedPackageWeek' key={week}>{Object.keys(daysByWeek).length>1&&<div className='sharedPackageWeekTitle'><b>Week {week}</b><span>{weekDays[0]?.date} – {weekDays[weekDays.length-1]?.date}</span></div>}<div className='sharedPackageDays'>{weekDays.map(day=>{const inactive=disabledDays.includes(day.date),dayCount=slotConfig.reduce((n,s)=>n+normalize(getSelected(day.date,s.id)).length,0),dayAddress=getDayAddress(day.date)||'';return <article className={'sharedPackageDay '+(inactive?'inactive ':'')+(day.warning?'closedDay':'')} key={day.date}><header className='sharedPackageDayHead'><div><b>{day.label||day.dayName||day.date}</b><span>{day.date}</span></div><strong>{dayCount} selected</strong></header>{day.warning&&<div className='sharedPackageDayNotice' role='note'><span>ⓘ</span><span>{day.warning}</span></div>}
 {showAddresses&&!inactive&&<div className='sharedPackageAddressBar'><label><span>{deliveryMode==='OneDeliveryPerDay'?'Delivery address':'Default address'}</span><select value={dayAddress} onChange={e=>onDayAddressChange(day.date,e.target.value)}><option value=''>Choose address…</option>{addresses.map(a=><option key={a.id} value={a.id}>{a.label} · {a.areaName||a.locality||a.city}</option>)}</select></label>{onAddAddress&&<button type='button' onClick={()=>onAddAddress({date:day.date})}>＋ Address</button>}</div>}
 <div className='sharedPackageSlots'>{slotConfig.map(slot=>{const options=menuFor(day.date,slot.id)||[],selected=normalize(getSelected(day.date,slot.id)),selectedIds=new Set(selected.map(x=>x.recipeId)),filter=activeFilter[day.date+'_'+slot.id]||'All',visible=filter==='All'?options:options.filter(x=>String(x.category||'')===filter),groups=Object.entries(visible.reduce((a,item)=>{const g=groupName(item);(a[g]??=[]).push(item);return a},{}));return <div className={'sharedPackageSlot '+(selected.length?'selected':'')+' '+(!options.length?'empty':'')} key={slot.id}>
 <div className='sharedPackageSlotHead'><div><span className='sharedPackageSlotIcon'>{slot.icon}</span><div><b>{slot.label}</b><small>{options.length?selected.length+' selected · '+options.length+' available':'No menu configured'}</small></div></div>{selected.length>0&&<button type='button' onClick={()=>onSelectionChange(day.date,slot.id,[])}>Clear</button>}</div>
 {options.length>0&&<div className='sharedPackageFilters'><button className={filter==='All'?'active':''} onClick={()=>setActiveFilter(v=>({...v,[day.date+'_'+slot.id]:'All'}))}>All</button>{[...new Set(options.map(x=>x.category).filter(Boolean))].slice(0,4).map(c=><button key={c} className={filter===c?'active':''} onClick={()=>setActiveFilter(v=>({...v,[day.date+'_'+slot.id]:c}))}>{c}</button>)}</div>}
 {groups.map(([group,items])=>{const max=Math.max(1,...items.map(x=>Number(x.maxSelections||1))),count=items.filter(x=>selectedIds.has(x.recipeId)).length,required=items.some(x=>x.isRequired);return <div className='sharedPackageGroup' key={group}><div className='sharedPackageGroupHead'><div><b>{group}</b><small>{required?'Required':'Optional'} · up to {max}</small></div><span>{count}/{max}</span></div><div className='sharedPackageOptions'>{items.map(item=>{const checked=selectedIds.has(item.recipeId),largeEnabled=showLargePortion!==false&&(showLargePortion===true||Number(item.largePricePerMeal||0)>0),atLimit=!checked&&count>=max,itemSelected=selected.find(x=>x.recipeId===item.recipeId);return <div className={'sharedPackageOption '+(checked?'checked':'')} key={item.recipeId}><button type='button' className='sharedPackageOptionMain' disabled={atLimit} onClick={()=>toggle(day.date,slot.id,item)}><span className='sharedPackageCheck'>{checked?'✓':'+'}</span><span><b>{item.recipeName}</b>{showPrice&&<small>{item.mealType||group} · {money(item.pricePerMeal)}</small>}</span></button>{checked&&showPortion&&<div className='sharedPackageControls'><label><span>Portion</span><select value={getPortion(day.date,slot.id,item.recipeId)||itemSelected?.portion||1} onChange={e=>onPortionChange(day.date,slot.id,item.recipeId,e.target.value)}><option value='1'>Regular</option>{largeEnabled&&<option value='2'>Large</option>}</select></label>{showAddresses&&deliveryMode==='IndividualMealDelivery'&&<label><span>Delivery</span><select value={getItemAddress(day.date,slot.id,item.recipeId)||''} onChange={e=>onItemAddressChange(day.date,slot.id,item.recipeId,e.target.value)}><option value=''>Use day address</option>{addresses.map(a=><option key={a.id} value={a.id}>{a.label}</option>)}</select></label>}</div>}</div>})}</div></div>})}
 {!options.length&&<div className='sharedPackageEmpty'><span>＋</span><div><b>{emptyMessage}</b><small>Ask the outlet to configure this day and slot in Weekly Menu.</small></div></div>}</div>})}</div></article>})}</div></div>)}
 </section>}