
import React,{useEffect,useMemo,useState}from'react';
import{createRoot}from'react-dom/client';
import{auth,outletAdmin,currentUser,money,API_URL}from'@healthapp/shared';
import'./styles.css';

const ORIGIN=API_URL.replace(/\/api\/?$/,'');
const img=u=>u?(u.startsWith('http')?u:ORIGIN+u):'';
const DAYS=['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday'];
const SLOTS=[['Breakfast',0],['Lunch',1],['Dinner',2],['Snack',3]];
const emptyRecipe={name:'',category:'Veg',calories:0,proteinGrams:0,carbsGrams:0,fatGrams:0,pricePerMeal:0,largePricePerMeal:0,description:'',ingredients:'',allergens:'',tags:'',imageUrl:'',isActive:true};

function Modal({title,onClose,children,wide}){return <div className="overlay" onMouseDown={e=>e.target===e.currentTarget&&onClose()}><div className={wide?'modal wide':'modal'}><div className="modalHead"><h3>{title}</h3><button className="iconBtn" onClick={onClose}>×</button></div>{children}</div></div>}
function Field({label,children,help}){return <label className="field"><span>{label}</span>{children}{help&&<small>{help}</small>}</label>}
function Empty({title,text}){return <div className="empty"><div className="emptyIcon">＋</div><h3>{title}</h3><p>{text}</p></div>}
function Table({columns,rows,empty}){return rows.length?<div className="dataTable"><div className="dataRow header">{columns.map(c=><span key={c}>{c}</span>)}</div>{rows.map((r,i)=><div className="dataRow" key={i}>{r.map((v,j)=><span key={j}>{v}</span>)}</div>)}</div>:<Empty title={empty} text="There is no activity to show yet."/>}

function App(){
 const[user,setUser]=useState(currentUser()),[login,setLogin]=useState({email:'admin@fitfood.test',password:'demo'}),[active,setActive]=useState('dashboard'),[dash,setDash]=useState(null);
 const[recipes,setRecipes]=useState([]),[pricing,setPricing]=useState([]),[areas,setAreas]=useState([]),[selectedAreas,setSelectedAreas]=useState([]),[tiers,setTiers]=useState([]);
 const[customers,setCustomers]=useState([]),[subs,setSubs]=useState([]),[orders,setOrders]=useState([]),[deliveries,setDeliveries]=useState([]),[menu,setMenu]=useState([]),[billing,setBilling]=useState(null);
 const[error,setError]=useState(''),[busy,setBusy]=useState(false),[toast,setToast]=useState(''),[search,setSearch]=useState(''),[category,setCategory]=useState('All'),[city,setCity]=useState('Bengaluru');
 const[recipeOpen,setRecipeOpen]=useState(false),[editRecipe,setEditRecipe]=useState(null),[recipeForm,setRecipeForm]=useState(emptyRecipe),[uploading,setUploading]=useState(false);
 const[pricingOpen,setPricingOpen]=useState(false),[priceForm,setPriceForm]=useState({maxDistanceKm:'',fee:''});
 const[tierOpen,setTierOpen]=useState(false),[editTier,setEditTier]=useState(null),[tierForm,setTierForm]=useState({minMeals:1,maxMeals:9,oneWeekPercent:0,twoWeeksPercent:0,oneMonthPercent:0});
 const notify=m=>{setToast(m);setTimeout(()=>setToast(''),2500)},fail=e=>setError(e?.message||'Unexpected error.');
 const load=async p=>{setBusy(true);setError('');try{
  if(p==='dashboard'){setDash(await outletAdmin.dashboard());setRecipes(await outletAdmin.recipes());setPricing(await outletAdmin.pricingRules());}
  if(p==='recipes')setRecipes(await outletAdmin.recipes());
  if(p==='customers')setCustomers(await outletAdmin.customers());
  if(p==='subscriptions')setSubs(await outletAdmin.subscriptions());
  if(p==='orders')setOrders(await outletAdmin.orders());
  if(p==='deliveries')setDeliveries(await outletAdmin.deliveries());
  if(p==='menu'){const x=await Promise.all([outletAdmin.menu(),outletAdmin.recipes()]);setMenu(x[0]);setRecipes(x[1])}
  if(p==='delivery-areas'){const x=await Promise.all([outletAdmin.availableDeliveryAreas(city),outletAdmin.selectedDeliveryAreas()]);setAreas(x[0]);setSelectedAreas(x[1].map(a=>a.cityAreaId))}
  if(p==='pricing')setPricing(await outletAdmin.pricingRules());
  if(p==='discounts')setTiers(await outletAdmin.discountTiers());
  if(p==='billing')setBilling(await outletAdmin.billing());
 }catch(e){fail(e)}finally{setBusy(false)}};
 useEffect(()=>{if(user)load(active)},[user,active]);
 useEffect(()=>{if(user&&active==='delivery-areas')load('delivery-areas')},[city]);
 const nav=p=>{setActive(p);setError('')};
 const signIn=async e=>{e.preventDefault();try{const x=await auth.login(login);setUser(x.user)}catch(e){fail(e)}};
 const filtered=useMemo(()=>recipes.filter(r=>(category==='All'||r.category===category)&&(!search||r.name.toLowerCase().includes(search.toLowerCase()))),[recipes,category,search]);

 const openNew=()=>{setEditRecipe(null);setRecipeForm({...emptyRecipe});setRecipeOpen(true)};
 const openEdit=r=>{setEditRecipe(r);setRecipeForm({...r});setRecipeOpen(true)};
 const upload=async file=>{if(!file)return;if(!file.type.startsWith('image/'))return fail({message:'Only image files are allowed.'});if(file.size>5000000)return fail({message:'Image must be 5 MB or smaller.'});try{setUploading(true);const r=await outletAdmin.uploadRecipeImage(file);setRecipeForm(f=>({...f,imageUrl:r.url}));notify('Image uploaded')}catch(e){fail(e)}finally{setUploading(false)}};
 const saveRecipe=async e=>{e.preventDefault();try{const p={...recipeForm,calories:Number(recipeForm.calories)||0,proteinGrams:Number(recipeForm.proteinGrams)||0,carbsGrams:Number(recipeForm.carbsGrams)||0,fatGrams:Number(recipeForm.fatGrams)||0,pricePerMeal:Number(recipeForm.pricePerMeal)||0,largePricePerMeal:Number(recipeForm.largePricePerMeal)||0};if(editRecipe)await outletAdmin.updateRecipe(editRecipe.id,p);else await outletAdmin.createRecipe(p);setRecipeOpen(false);await load('recipes');notify(editRecipe?'Recipe updated':'Recipe created')}catch(e){fail(e)}};
 const removeRecipe=async r=>{if(!confirm('Delete '+r.name+'?'))return;try{await outletAdmin.deleteRecipe(r.id);await load('recipes');notify('Recipe deleted')}catch(e){fail(e)}};
 const addPrice=async e=>{e.preventDefault();const km=Number(priceForm.maxDistanceKm),fee=Number(priceForm.fee);if(km<=0)return fail({message:'Distance must be greater than 0.'});if(fee<0)return fail({message:'Fee cannot be negative.'});if(pricing.some(x=>Number(x.maxDistanceKm)===km))return fail({message:'This distance slab already exists.'});try{await outletAdmin.addPricingRule({maxDistanceKm:km,fee});setPricingOpen(false);setPriceForm({maxDistanceKm:'',fee:''});await load('pricing');notify('Delivery slab added')}catch(e){fail(e)}};
 const removePrice=async r=>{if(!confirm('Delete the '+r.maxDistanceKm+' km slab?'))return;try{await outletAdmin.deletePricingRule(r.id);await load('pricing');notify('Delivery slab removed')}catch(e){fail(e)}};
 const saveAreas=async()=>{try{await outletAdmin.saveDeliveryAreas(selectedAreas);await load('delivery-areas');notify('Delivery areas saved')}catch(e){fail(e)}};
 const saveTier=async e=>{e.preventDefault();const p={minMeals:Number(tierForm.minMeals),maxMeals:tierForm.maxMeals===''?null:Number(tierForm.maxMeals),oneWeekPercent:Number(tierForm.oneWeekPercent),twoWeeksPercent:Number(tierForm.twoWeeksPercent),oneMonthPercent:Number(tierForm.oneMonthPercent),isActive:true};try{if(editTier)await outletAdmin.updateDiscountTier(editTier.id,p);else await outletAdmin.addDiscountTier(p);setTierOpen(false);await load('discounts');notify('Discount tier saved')}catch(e){fail(e)}};
 const removeTier=async r=>{if(!confirm('Delete this discount tier?'))return;try{await outletAdmin.deleteDiscountTier(r.id);await load('discounts');notify('Discount tier removed')}catch(e){fail(e)}};

 if(!user)return <div className="loginPage"><div className="loginCard"><div className="brand"><span className="brandMark">H</span><div><b>HealthApp</b><small>Outlet management</small></div></div><h1>Welcome back</h1><p>Run your meal business from one workspace.</p><form onSubmit={signIn}><Field label="Email"><input value={login.email} onChange={e=>setLogin({...login,email:e.target.value})}/></Field><Field label="Password"><input type="password" value={login.password} onChange={e=>setLogin({...login,password:e.target.value})}/></Field><button className="primary full">Sign in</button>{error&&<div className="error">{error}</div>}<small className="demo">Demo: admin@fitfood.test / demo</small></form></div></div>;

 const navs=[['dashboard','⌂','Dashboard'],['recipes','◈','Recipes'],['menu','☷','Weekly Menu'],['customers','♙','Customers'],['subscriptions','◫','Subscriptions'],['orders','▤','Orders'],['deliveries','⌁','Deliveries'],['delivery-areas','⌖','Delivery Areas'],['pricing','₹','Delivery Pricing'],['discounts','%','Discounts'],['billing','▣','Billing']];
 const title=navs.find(n=>n[0]===active)?.[2]||'Dashboard';
 return <div className="appShell"><aside className="sidebar"><div className="sideBrand"><span className="brandMark">H</span><div><b>HealthApp</b><small>Outlet portal</small></div></div><div className="outletMini"><div className="avatar">{(dash?.outlet?.name||'F')[0]}</div><div><b>{dash?.outlet?.name||'FitFood Bengaluru'}</b><span>Outlet Admin</span></div></div><div className="navLabel">Workspace</div>{navs.slice(0,7).map(n=><button className={active===n[0]?'navItem active':'navItem'} key={n[0]} onClick={()=>nav(n[0])}><span>{n[1]}</span>{n[2]}</button>)}<div className="navLabel">Configuration</div>{navs.slice(7).map(n=><button className={active===n[0]?'navItem active':'navItem'} key={n[0]} onClick={()=>nav(n[0])}><span>{n[1]}</span>{n[2]}</button>)}<div className="sideBottom"><div className="secure">● API connected</div><button className="logoutBtn" onClick={()=>{auth.logout();setUser(null)}}>Log out</button></div></aside>
 <section className="main"><header className="topbar"><div><h2>{title}</h2><span>{dash?.outlet?.city||'Bengaluru'}, {dash?.outlet?.state||'Karnataka'}</span></div><div className="topUser"><div className="avatar sm">{(user.firstName||'A')[0]}</div><div><b>{user.firstName} {user.lastName}</b><span>{user.email}</span></div></div></header>
 <main className="content">{error&&<div className="bannerError"><span>{error}</span><button onClick={()=>setError('')}>Dismiss</button></div>}
 {active==='dashboard'&&<Dashboard dash={dash} recipes={recipes} pricing={pricing} nav={nav}/>}
 {active==='recipes'&&<Recipes items={filtered} total={recipes.length} search={search} setSearch={setSearch} category={category} setCategory={setCategory} openNew={openNew} openEdit={openEdit} remove={removeRecipe}/>}
 {active==='menu'&&<MenuPage recipes={recipes} menu={menu} setMenu={setMenu} onSave={async()=>{try{await outletAdmin.saveMenu(menu.map(x=>({recipeId:x.recipeId,dayOfWeek:Number(x.dayOfWeek),mealSlot:Number(x.mealSlot),isAvailable:x.isAvailable,displayOrder:x.displayOrder||0})));notify('Weekly menu saved')}catch(e){fail(e)}}}/>}
 {active==='customers'&&<Page title="Customers" text="Customers connected to this outlet." content={<Table columns={['Name','Email','Role']} rows={customers.map(x=>[x.firstName+' '+x.lastName,x.email,x.role])} empty="No customers yet."/>}/>}
 {active==='subscriptions'&&<Page title="Subscriptions" text="Customer packages and delivery schedules." content={<Table columns={['Plan','Customer','Status','Meals','Next delivery','Total']} rows={subs.map(x=>[x.planName,String(x.customerId).slice(0,8)+'…',x.status,x.mealsPerWeek,new Date(x.nextDeliveryDate).toLocaleDateString(),money(x.totalCharged)])} empty="No subscriptions yet."/>}/>}
 {active==='orders'&&<Page title="Orders" text="Orders generated from customer subscriptions." content={<Table columns={['Order','Customer','Status','Delivery date','Total']} rows={orders.map(x=>[String(x.id).slice(0,8)+'…',String(x.customerId).slice(0,8)+'…',x.status,new Date(x.deliveryDate).toLocaleDateString(),money(x.total)])} empty="No orders yet."/>}/>}
 {active==='deliveries'&&<Page title="Deliveries" text="Scheduled delivery jobs for this outlet." content={<Table columns={['Customer','Address','Date','Slot','Fee','Status']} rows={deliveries.map(x=>[x.customerName,x.address,new Date(x.scheduledDate).toLocaleDateString(),x.mealSlot,money(x.deliveryFee),x.status])} empty="No deliveries yet."/>}/>}
 {active==='delivery-areas'&&<Areas city={city} setCity={setCity} areas={areas} selected={selectedAreas} setSelected={setSelectedAreas} save={saveAreas}/>}
 {active==='pricing'&&<Pricing pricing={pricing} add={()=>setPricingOpen(true)} remove={removePrice}/>}
 {active==='discounts'&&<Discounts tiers={tiers} add={()=>{setEditTier(null);setTierForm({minMeals:1,maxMeals:9,oneWeekPercent:0,twoWeeksPercent:0,oneMonthPercent:0});setTierOpen(true)}} edit={t=>{setEditTier(t);setTierForm({...t,maxMeals:t.maxMeals??''});setTierOpen(true)}} remove={removeTier}/>}
 {active==='billing'&&<Billing billing={billing}/>}
 {busy&&<div className="loadingBar"><span/></div>}</main></section>
 {toast&&<div className="toast">✓ {toast}</div>}
 {recipeOpen&&<Modal title={editRecipe?'Edit recipe':'Create new recipe'} onClose={()=>setRecipeOpen(false)} wide><RecipeForm form={recipeForm} setForm={setRecipeForm} upload={upload} uploading={uploading} submit={saveRecipe} cancel={()=>setRecipeOpen(false)}/></Modal>}
 {pricingOpen&&<Modal title="Add delivery pricing slab" onClose={()=>setPricingOpen(false)}><form onSubmit={addPrice} className="formGrid"><Field label="Maximum distance (km)" help="Example: 2, 5, 10, 15, 20."><input type="number" min=".1" step=".1" value={priceForm.maxDistanceKm} onChange={e=>setPriceForm({...priceForm,maxDistanceKm:e.target.value})} required/></Field><Field label="Delivery fee (₹)"><input type="number" min="0" step=".01" value={priceForm.fee} onChange={e=>setPriceForm({...priceForm,fee:e.target.value})} required/></Field><div className="modalActions"><button type="button" className="secondary" onClick={()=>setPricingOpen(false)}>Cancel</button><button className="primary">Add slab</button></div></form></Modal>}
 {tierOpen&&<Modal title={editTier?'Edit discount tier':'Add discount tier'} onClose={()=>setTierOpen(false)}><form onSubmit={saveTier} className="formGrid"><Field label="Minimum meals"><input type="number" min="1" value={tierForm.minMeals} onChange={e=>setTierForm({...tierForm,minMeals:e.target.value})}/></Field><Field label="Maximum meals"><input type="number" min="1" placeholder="Blank for open-ended" value={tierForm.maxMeals} onChange={e=>setTierForm({...tierForm,maxMeals:e.target.value})}/></Field><Field label="1 week %"><input type="number" min="0" max="100" step=".01" value={tierForm.oneWeekPercent} onChange={e=>setTierForm({...tierForm,oneWeekPercent:e.target.value})}/></Field><Field label="2 weeks %"><input type="number" min="0" max="100" step=".01" value={tierForm.twoWeeksPercent} onChange={e=>setTierForm({...tierForm,twoWeeksPercent:e.target.value})}/></Field><Field label="1 month %"><input type="number" min="0" max="100" step=".01" value={tierForm.oneMonthPercent} onChange={e=>setTierForm({...tierForm,oneMonthPercent:e.target.value})}/></Field><div className="modalActions"><button type="button" className="secondary" onClick={()=>setTierOpen(false)}>Cancel</button><button className="primary">Save tier</button></div></form></Modal>}
 </div>
}
function Dashboard({dash,recipes,pricing,nav}){return <div className="page"><div className="hero"><div><div className="eyebrow">OUTLET OVERVIEW</div><h1>Good morning 👋</h1><p>Manage meals, weekly menu, customers and delivery operations from one workspace.</p></div><button className="primary" onClick={()=>nav('recipes')}>+ Add recipe</button></div><div className="statGrid">{[['recipes','Recipes',dash?.recipes||recipes.length],['customers','Customers',dash?.customers||0],['subscriptions','Subscriptions',dash?.subscriptions||0],['orders','Orders',dash?.orders||0]].map(s=><button className="statCard" key={s[0]} onClick={()=>nav(s[0])}><div><span>{s[1]}</span><b>{s[2]}</b></div><i>→</i></button>)}</div><div className="twoCol"><section className="panel"><div className="panelHead"><div><h3>Recipe catalogue</h3><p>Meals customers can select</p></div><button className="linkBtn" onClick={()=>nav('recipes')}>Manage →</button></div>{recipes.slice(0,6).map(r=><div className="miniRow" key={r.id}><div className="thumb">{r.imageUrl?<img src={img(r.imageUrl)}/>:r.name[0]}</div><div><b>{r.name}</b><span>{r.category} · {r.calories} kcal · {money(r.pricePerMeal)}</span></div><span className="pill green">Active</span></div>)}{!recipes.length&&<Empty title="No recipes" text="Create your first meal."/>}</section><section className="panel"><div className="panelHead"><div><h3>Delivery pricing</h3><p>Distance-based fees</p></div><button className="linkBtn" onClick={()=>nav('pricing')}>Configure →</button></div>{pricing.map(p=><div className="priceRow" key={p.id}><span>Up to {p.maxDistanceKm} km</span><b>{money(p.fee)}</b></div>)}{!pricing.length&&<Empty title="No slabs" text="Add the first pricing rule."/>}</section></div></div>}
function Page({title,text,content}){return <div className="page"><div className="pageHead"><div><h1>{title}</h1><p>{text}</p></div></div><section className="panel">{content}</section></div>}
function Recipes({items,total,search,setSearch,category,setCategory,openNew,openEdit,remove}){return <div className="page"><div className="pageHead"><div><h1>Recipes</h1><p>Create meals with image, ingredients, description, nutrition, allergens and pricing.</p></div><button className="primary" onClick={openNew}>+ New recipe</button></div><div className="toolbar"><input className="search" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search recipes…"/><select value={category} onChange={e=>setCategory(e.target.value)}><option>All</option><option>Veg</option><option>NonVeg</option><option>Vegan</option><option>Eggetarian</option><option>Pescatarian</option></select><span className="count">{items.length} / {total}</span></div>{!items.length?<Empty title="No matching recipes" text="Try another filter or create a recipe."/>:<div className="recipeGrid">{items.map(r=><article className="recipeCard" key={r.id}><div className="recipeImage">{r.imageUrl?<img src={img(r.imageUrl)} alt=""/>:<div className="placeholderImage">{r.name[0]}</div>}<span className="badge green">Active</span></div><div className="recipeBody"><div className="recipeTitle"><div><h3>{r.name}</h3><small>{r.category}</small></div><b>{money(r.pricePerMeal)}</b></div><p>{r.description||'No description yet.'}</p><div className="nutrition"><span><b>{r.calories}</b>kcal</span><span><b>{r.proteinGrams}g</b>protein</span><span><b>{r.carbsGrams}g</b>carbs</span><span><b>{r.fatGrams}g</b>fat</span></div><div className="recipeMeta"><span>{r.ingredients?'Ingredients added':'Ingredients missing'}</span><span>{r.allergens||'No allergens'}</span></div><div className="cardActions"><button className="secondary" onClick={()=>openEdit(r)}>Edit</button><button className="dangerText" onClick={()=>remove(r)}>Delete</button></div></div></article>)}</div>}</div>}
function RecipeForm({form,setForm,upload,uploading,submit,cancel}){const set=(k,v)=>setForm(f=>({...f,[k]:v}));return <form onSubmit={submit}><div className="recipeEditor"><div className="imageUpload"><div className="uploadPreview">{form.imageUrl?<img src={img(form.imageUrl)} alt="preview"/>:<div><span>＋</span><p>Upload meal photo</p><small>JPG, PNG, WEBP · 5 MB max</small></div>}</div><label className="uploadBtn">{uploading?'Uploading…':form.imageUrl?'Replace image':'Upload image'}<input type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>upload(e.target.files?.[0])}/></label></div><div className="formGrid"><Field label="Recipe name"><input value={form.name} onChange={e=>set('name',e.target.value)} required/></Field><Field label="Category"><select value={form.category} onChange={e=>set('category',e.target.value)}><option>Veg</option><option>NonVeg</option><option>Vegan</option><option>Eggetarian</option><option>Pescatarian</option></select></Field><Field label="Regular price (₹)"><input type="number" min="0" step=".01" value={form.pricePerMeal} onChange={e=>set('pricePerMeal',e.target.value)}/></Field><Field label="Large price (₹)"><input type="number" min="0" step=".01" value={form.largePricePerMeal} onChange={e=>set('largePricePerMeal',e.target.value)}/></Field><Field label="Calories"><input type="number" min="0" value={form.calories} onChange={e=>set('calories',e.target.value)}/></Field><Field label="Protein (g)"><input type="number" min="0" value={form.proteinGrams} onChange={e=>set('proteinGrams',e.target.value)}/></Field><Field label="Carbs (g)"><input type="number" min="0" value={form.carbsGrams} onChange={e=>set('carbsGrams',e.target.value)}/></Field><Field label="Fat (g)"><input type="number" min="0" value={form.fatGrams} onChange={e=>set('fatGrams',e.target.value)}/></Field><Field label="Description"><textarea value={form.description} onChange={e=>set('description',e.target.value)} placeholder="Describe the meal…"/></Field><Field label="Ingredients"><textarea value={form.ingredients||''} onChange={e=>set('ingredients',e.target.value)} placeholder="Chicken, brown rice, broccoli…"/></Field><Field label="Allergens"><input value={form.allergens||''} onChange={e=>set('allergens',e.target.value)} placeholder="Milk, nuts…"/></Field><Field label="Tags"><input value={form.tags||''} onChange={e=>set('tags',e.target.value)} placeholder="High protein, low carb…"/></Field><Field label="Image URL"><input value={form.imageUrl||''} onChange={e=>set('imageUrl',e.target.value)} placeholder="https://…"/></Field></div></div><div className="modalActions"><button type="button" className="secondary" onClick={cancel}>Cancel</button><button className="primary" disabled={uploading}>{form.id?'Save changes':'Create recipe'}</button></div></form>}
function MenuPage({recipes,menu,setMenu,onSave}){const[day,setDay]=useState(1),[slot,setSlot]=useState(1),[rid,setRid]=useState('');useEffect(()=>{if(!rid&&recipes[0])setRid(recipes[0].id)},[recipes,rid]);const add=()=>{const r=recipes.find(x=>x.id===rid);if(!r)return;if(menu.some(x=>Number(x.dayOfWeek)===day&&Number(x.mealSlot)===slot&&x.recipeId===rid))return;setMenu([...menu,{id:'tmp-'+Date.now(),recipeId:rid,recipeName:r.name,dayOfWeek:day,mealSlot:slot,isAvailable:true,displayOrder:0}])};return <div className="page"><div className="pageHead"><div><h1>Weekly Menu</h1><p>Configure which meals are available on each day and slot.</p></div><button className="primary" onClick={onSave}>Save weekly menu</button></div><div className="menuControls"><select value={day} onChange={e=>setDay(Number(e.target.value))}>{DAYS.map((d,i)=><option value={i} key={d}>{d}</option>)}</select><select value={slot} onChange={e=>setSlot(Number(e.target.value))}>{SLOTS.map(s=><option value={s[1]} key={s[1]}>{s[0]}</option>)}</select><select value={rid} onChange={e=>setRid(e.target.value)}><option value="">Choose recipe…</option>{recipes.map(r=><option value={r.id} key={r.id}>{r.name}</option>)}</select><button className="secondary" onClick={add}>+ Add item</button></div><div className="menuWeek">{DAYS.map((d,i)=><section className={i===day?'dayCard selected':'dayCard'} key={d} onClick={()=>setDay(i)}><div className="dayHead"><b>{d}</b><span>{menu.filter(m=>Number(m.dayOfWeek)===i&&m.isAvailable).length} available</span></div>{menu.filter(m=>Number(m.dayOfWeek)===i).map(m=><div className="menuItem" key={m.id}><div><b>{m.recipeName||((recipes.find(r=>r.id===m.recipeId)||{}).name)||'Meal'}</b><span>{((SLOTS.find(s=>s[1]===Number(m.mealSlot))||[])[0])||m.mealSlot}</span></div><div><input type="checkbox" checked={m.isAvailable} onChange={e=>setMenu(menu.map(x=>x.id===m.id?{...x,isAvailable:e.target.checked}:x))}/><button className="iconBtn small" onClick={e=>{e.stopPropagation();setMenu(menu.filter(x=>x.id!==m.id))}}>×</button></div></div>)}{!menu.some(m=>Number(m.dayOfWeek)===i)&&<div className="dayEmpty">No items</div>}</section>)}</div></div>}
function Areas({city,setCity,areas,selected,setSelected,save}){return <div className="page"><div className="pageHead"><div><h1>Delivery Areas</h1><p>Select the master city areas this outlet serves.</p></div><button className="primary" onClick={save}>Save selected</button></div><div className="notice"><b>Customer address rule:</b><span>Only selected areas can be used for this outlet.</span></div><div className="toolbar"><input value={city} onChange={e=>setCity(e.target.value)} placeholder="City"/><span className="count">{selected.length} selected</span></div><div className="areaGrid">{areas.map(a=><label className={selected.includes(a.id)?'areaCard checked':'areaCard'} key={a.id}><input type="checkbox" checked={selected.includes(a.id)} onChange={e=>setSelected(e.target.checked?[...selected,a.id]:selected.filter(x=>x!==a.id))}/><div><b>{a.name}</b><span>{a.city}, {a.state}</span><small>{a.pincode}</small></div></label>)}</div></div>}
function Pricing({pricing,add,remove}){return <div className="page"><div className="pageHead"><div><h1>Delivery Pricing</h1><p>Configure distance-based delivery fees for customers.</p></div><button className="primary" onClick={add}>+ Add distance slab</button></div><div className="pricingExplain"><span>Customer address</span><b>→</b><span>Distance calculated</span><b>→</b><span>Matching slab fee</span></div><section className="panel">{pricing.length?<div className="pricingTable"><div className="ptHead"><span>Up to distance</span><span>Fee</span><span>Action</span></div>{pricing.map(p=><div className="ptRow" key={p.id}><b>≤ {p.maxDistanceKm} km</b><strong>{money(p.fee)}</strong><button className="dangerText" onClick={()=>remove(p)}>Delete</button></div>)}</div>:<Empty title="No pricing slabs" text="Start with 2 km = ₹10, then add larger distance slabs."/>}</section></div>}
function Discounts({tiers,add,edit,remove}){return <div className="page"><div className="pageHead"><div><h1>Subscription Discounts</h1><p>Discounts based on committed meal quantity and package duration.</p></div><button className="primary" onClick={add}>+ Add tier</button></div><section className="panel"><div className="discountTable"><div className="dtRow header"><span>Meals</span><span>1W</span><span>2W</span><span>1M</span><span>Actions</span></div>{tiers.map(t=><div className="dtRow" key={t.id}><b>{t.minMeals} – {t.maxMeals??'∞'}</b><span>{t.oneWeekPercent}%</span><span>{t.twoWeeksPercent}%</span><span>{t.oneMonthPercent}%</span><div><button className="secondary smallBtn" onClick={()=>edit(t)}>Edit</button><button className="dangerText" onClick={()=>remove(t)}>Delete</button></div></div>)}</div>{!tiers.length&&<Empty title="No discount tiers" text="Create your first quantity-based discount."/>}</section></div>}
function Billing({billing}){return <div className="page"><div className="pageHead"><div><h1>Billing</h1><p>Current outlet SaaS subscription and commission details.</p></div></div>{billing?<div className="billingGrid"><section className="panel"><span className="eyebrow">CURRENT PLAN</span><h2>{billing.planName}</h2><div className="bigMoney">{money(billing.subscriptionFee)}<small> / {billing.billingCycle}</small></div><div className="kv"><span>Commission</span><b>{billing.transactionFeePercent}%</b></div><div className="kv"><span>Included customers</span><b>{billing.includedActiveCustomers}</b></div><div className="kv"><span>Active customers</span><b>{billing.activeCustomers}</b></div></section><section className="panel"><h3>Plan details</h3><div className="kv"><span>Setup fee</span><b>{money(billing.setupFee)}</b></div><div className="kv"><span>Renewal</span><b>{new Date(billing.renewalDate).toLocaleDateString()}</b></div><div className="kv"><span>Status</span><span className="pill green">{billing.status}</span></div></section></div>:<Empty title="Billing unavailable" text="The outlet has no active SaaS subscription."/>}</div>}
createRoot(document.getElementById('root')).render(<App/>);
