import React,{useEffect,useState}from'react';
import{outletOnboarding}from'@healthapp/shared';

const isRegistered=x=>String(x?.businessType||'').toLowerCase().replace(/[^a-z]/g,'')==='registeredbusiness';
const EMPTY={businessType:'Individual',outletName:'',description:'',city:'',state:'',pincode:'',addressLine1:'',addressLine2:'',ownerName:'',ownerEmail:'',ownerPhone:'',aadhaarNumber:'',businessPan:'',gstNumber:''};

function Doc({title,required,fileName,onUpload,loading}){return <div className="verificationDoc"><div><b>{title}</b>{required&&<span className="requiredTag">Required</span>}<small>{fileName?('Uploaded: '+fileName):'Not uploaded yet'}</small></div><button type="button" className={fileName?'linkBtn':'secondary'} onClick={onUpload} disabled={loading}>{loading?'Uploading…':fileName?'Replace':'Upload'}</button></div>}

export default function OutletVerificationCenter({user,onLogout}){
 const[app,setApp]=useState(null),[details,setDetails]=useState(EMPTY),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[uploading,setUploading]=useState(''),[error,setError]=useState(''),[message,setMessage]=useState('');
 const load=async()=>{try{setLoading(true);setError('');const x=await outletOnboarding.me();setApp(x);setDetails({businessType:x?.businessType||'Individual',outletName:x?.outletName||'',description:x?.description||'',city:x?.city||'',state:x?.state||'',pincode:x?.pincode||'',addressLine1:x?.addressLine1||'',addressLine2:x?.addressLine2||'',ownerName:x?.ownerName||'',ownerEmail:x?.ownerEmail||user?.email||'',ownerPhone:x?.ownerPhone||'',aadhaarNumber:x?.aadhaarNumber||'',businessPan:x?.businessPan||'',gstNumber:x?.gstNumber||''})}catch(e){setError(e.message||'Unable to load verification details.')}finally{setLoading(false)}};
 useEffect(()=>{load()},[]);
 const docs=t=>app?.documents?.find(x=>x.documentType===t);
 const upload=type=>{const input=document.createElement('input');input.type='file';input.accept='.jpg,.jpeg,.png,.webp,.pdf';input.onchange=async()=>{const file=input.files?.[0];if(!file)return;if(file.size>20000000){setError('Document must be 20 MB or smaller. Original documents are kept unchanged for verification.');return;}try{setUploading(type);setError('');await outletOnboarding.uploadCurrentDocument(type,file);await load();setMessage('Document uploaded.')}catch(e){setError(e.message||'Upload failed')}finally{setUploading('')}};input.click()};
 const save=async e=>{e.preventDefault();try{setSaving(true);setError('');const x=await outletOnboarding.saveCurrentDetails({...details,aadhaarNumber:details.aadhaarNumber.trim(),businessPan:details.businessPan.trim().toUpperCase(),gstNumber:details.gstNumber.trim().toUpperCase()});setApp(x);setMessage('Verification details saved.')}catch(e){setError(e.message||'Unable to save details')}finally{setSaving(false)}};
 const submit=async()=>{try{setSaving(true);setError('');const x=await outletOnboarding.submitCurrent();setApp(x);setMessage('Your application has been submitted for verification.')}catch(e){setError(e.message||'Unable to submit for verification')}finally{setSaving(false)}};
 if(loading)return <div className="verificationGate"><div className="verificationGateCard"><div className="successIcon">◷</div><h1>Loading verification centre…</h1></div></div>;
 const rejected=app?.status==='Rejected', under=app?.status==='UnderVerification', registered=isRegistered(details);
 const ready=!!details.aadhaarNumber&&!!docs('AadhaarCard')&&(!registered|| (!!details.businessPan&&!!docs('BusinessPan')&&!!details.gstNumber&&!!docs('GstCertificate')&&!!docs('BusinessRegistration')));
 return <div className="verificationGate"><header className="verificationGateHeader"><div className="onboardingBrand"><span className="brandMark">H</span><div><b>HealthApp</b><small>Outlet verification</small></div></div><div className="verificationGateAccount"><span>{user?.email}</span><button type="button" className="onboardingExit" onClick={onLogout}>Log out</button></div></header><main className="verificationGateMain"><section className="verificationGateIntro"><span className="landingKicker">{rejected?'ACTION REQUIRED':under?'UNDER VERIFICATION':'COMPLETE YOUR SETUP'}</span><h1>{rejected?'Update your details and resubmit.':'Your outlet account is created. Complete verification to activate it.'}</h1><p>You can now sign in and finish the remaining business verification details. Your outlet workspace will be unlocked once HealthApp approves the application.</p></section>{error&&<div className="statusBanner error"><span>{error}</span><button type="button" onClick={()=>setError('')}>×</button></div>}{message&&<div className="verificationMessage">✓ {message}</div>}
 <section className="verificationStatusCard"><div className="verificationStepsCompact"><div className="done"><strong>✓</strong><span>Account created</span></div><i></i><div className={under||rejected?'current':'done'}><strong>{under?'◷':rejected?'!':'2'}</strong><span>Complete verification</span></div><i></i><div><strong>3</strong><span>HealthApp approval</span></div><i></i><div><strong>4</strong><span>Workspace activated</span></div></div><div className="verificationStatusText"><b>{under?'Submitted and awaiting review':rejected?'Application rejected — update the details below':'Verification details are ready to be completed'}</b><small>Plan: {app?.planName} · {app?.billingCycle} · Setup payment: {app?.paymentStatus}</small></div></section>
 <form className="verificationForm" onSubmit={save}><section className="verificationPanelCard"><div className="verificationPanelHead"><div><span>01</span><div><h2>Business details</h2><small>These can be corrected after your account is created.</small></div></div></div><div className="verificationFormGrid"><label className="field"><span>Outlet name *</span><input value={details.outletName} onChange={e=>setDetails({...details,outletName:e.target.value})} required/></label><label className="field"><span>Business type *</span><select value={details.businessType} onChange={e=>setDetails({...details,businessType:e.target.value})}><option value="Individual">Individual / Unregistered</option><option value="RegisteredBusiness">Registered business</option></select></label><label className="field"><span>City *</span><input value={details.city} onChange={e=>setDetails({...details,city:e.target.value})} required/></label><label className="field"><span>State *</span><input value={details.state} onChange={e=>setDetails({...details,state:e.target.value})} required/></label><label className="field"><span>Pincode *</span><input value={details.pincode} onChange={e=>setDetails({...details,pincode:e.target.value})} required/></label><label className="field"><span>Owner name *</span><input value={details.ownerName} onChange={e=>setDetails({...details,ownerName:e.target.value})} required/></label><label className="field"><span>Owner email</span><input value={details.ownerEmail} disabled/></label><label className="field"><span>Contact number *</span><input value={details.ownerPhone} onChange={e=>setDetails({...details,ownerPhone:e.target.value})} required/></label><label className="field span2"><span>Address line 1 *</span><input value={details.addressLine1} onChange={e=>setDetails({...details,addressLine1:e.target.value})} required/></label><label className="field span2"><span>Address line 2</span><input value={details.addressLine2} onChange={e=>setDetails({...details,addressLine2:e.target.value})}/></label><label className="field span2"><span>Description</span><textarea rows="3" value={details.description} onChange={e=>setDetails({...details,description:e.target.value})}/></label></div></section>
 <section className="verificationPanelCard"><div className="verificationPanelHead"><div><span>02</span><div><h2>Identity & business documents</h2><small>Upload these after signing in. HealthApp stores them with your verification application.</small></div></div></div><div className="verificationFormGrid"><label className="field"><span>Aadhaar number *</span><input inputMode="numeric" pattern="[0-9]{12}" maxLength="12" value={details.aadhaarNumber} onChange={e=>setDetails({...details,aadhaarNumber:e.target.value.replace(/\D/g,'').slice(0,12)})} required/></label><label className="field"><span>Business PAN {registered?'*':''}</span><input value={details.businessPan} onChange={e=>setDetails({...details,businessPan:e.target.value.toUpperCase()})} required={registered}/></label><label className="field"><span>GST number {registered?'*':''}</span><input value={details.gstNumber} onChange={e=>setDetails({...details,gstNumber:e.target.value.toUpperCase()})} required={registered}/></label></div><div className="verificationDocsGrid"><Doc title="Aadhaar card" required fileName={docs('AadhaarCard')?.fileName} onUpload={()=>upload('AadhaarCard')} loading={uploading==='AadhaarCard'}/>{registered&&<><Doc title="Business registration" required fileName={docs('BusinessRegistration')?.fileName} onUpload={()=>upload('BusinessRegistration')} loading={uploading==='BusinessRegistration'}/><Doc title="Business PAN" required fileName={docs('BusinessPan')?.fileName} onUpload={()=>upload('BusinessPan')} loading={uploading==='BusinessPan'}/><Doc title="GST certificate" required fileName={docs('GstCertificate')?.fileName} onUpload={()=>upload('GstCertificate')} loading={uploading==='GstCertificate'}/></>}</div></section>
 <section className="verificationSubmitCard"><div><b>{ready?'Everything required is ready.':'Complete the required information and documents.'}</b><small>{ready?'Submit your application for HealthApp review.':'You can save now and return later from the same account.'}</small></div><div><button type="submit" className="secondary" disabled={saving||under}>{saving?'Saving…':'Save verification details'}</button><button type="button" className="primary" disabled={saving||under||!ready} onClick={submit}>{under?'Already submitted':saving?'Submitting…':rejected?'Resubmit for verification':'Submit for verification'}</button></div></section></form></main></div>;
}
