import React,{useEffect,useState}from'react';
import{money,outletAdmin,CUSTOMER_URL}from'@healthapp/shared';
import{MapContainer,TileLayer,CircleMarker,Circle}from'react-leaflet';
import'leaflet/dist/leaflet.css';

const DAYS=['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday'];
const SECTIONS=[['overview','⚡','Launch checklist'],['branding','✦','Branding'],['domains','⌁','Domains'],['delivery','⌖','Delivery schedule'],['areas','◎','Service coverage'],['pricing','₹','Delivery pricing'],['discounts','%','Subscription discounts'],['meal-plans','▣','Meal plans'],['tax','▤','Tax & GST'],['legal','§','Legal & policies'],['billing','▣','HealthApp billing']];

export default function OutletSettings({onNavigate}){
 const[section,setSection]=useState('overview');
 const[data,setData]=useState(null),[readiness,setReadiness]=useState(null),[domains,setDomains]=useState([]),[areas,setAreas]=useState([]),[selectedAreas,setSelectedAreas]=useState([]),[pricing,setPricing]=useState([]),[tiers,setTiers]=useState([]),[mealPlans,setMealPlans]=useState([]),[saasPlans,setSaasPlans]=useState([]),[billing,setBilling]=useState(null);
 const[deliveryDays,setDeliveryDays]=useState([]),[coverageMode,setCoverageMode]=useState('Radius'),[serviceRadiusKm,setServiceRadiusKm]=useState(20),[priceForm,setPriceForm]=useState({maxDistanceKm:'',fee:''}),[tierForm,setTierForm]=useState({minMeals:1,maxMeals:9,oneWeekPercent:0,twoWeeksPercent:0,oneMonthPercent:0}),[editTier,setEditTier]=useState(null),[mealPlanForm,setMealPlanForm]=useState({name:'',frequency:'Weekly',mealsPerDay:1,mealsPerWeek:7,price:0,currency:'INR',description:''});
 const[domainForm,setDomainForm]=useState({hostname:'',isPrimary:false}),[planChoice,setPlanChoice]=useState(''),[cycle,setCycle]=useState('Monthly'),[tax,setTax]=useState({restaurantGstRate:5,restaurantGstMode:'Exclusive'}),[branding,setBranding]=useState({brandName:'',tagline:'',logoUrl:'',heroImageUrl:'',faviconUrl:'',primaryColor:'#14532d',secondaryColor:'#166534',healthHighlights:'',about:'',footerText:'',fontFamily:'Inter',themeStyle:'Fresh',buttonStyle:'Rounded',cardStyle:'Soft'}),[brandingUploading,setBrandingUploading]=useState(''),[saving,setSaving]=useState(false),[error,setError]=useState(''),[toast,setToast]=useState(''),[confirmLive,setConfirmLive]=useState(false),[previewOpen,setPreviewOpen]=useState(false);

 const getCustomerPreviewUrl=()=>{const custom=[...domains].reverse().find(d=>d.type==='Custom'&&String(d.status).toLowerCase()==='active'&&d.isPrimary)?.hostname;const platform=domains.find(d=>d.type==='Platform'&&d.hostname)?.hostname;const host=window.location.hostname;const isLocal=host==='localhost'||host==='127.0.0.1'||host==='::1';const base=custom?('https://'+custom):(platform&&!isLocal?'https://'+platform:CUSTOMER_URL.replace(/\/$/,''));if(!base)return '';const separator=base.includes('?')?'&':'?';const slug=data?.outletSlug||'';return slug?base+separator+'outlet='+encodeURIComponent(slug):base;};
 const getCustomerLegalUrl=id=>{const base=getCustomerPreviewUrl();if(!base)return '';const clean=base.replace(/([?&])outlet=[^&]*/,'').replace(/[?&]$/,'');return clean+(clean.includes('?')?'&':'?')+'legal='+encodeURIComponent(id);};
 const load=async()=>{try{setSaving(true);setError('');const[s,r,ds,a,ar,p,t,b,mp,sp]=await Promise.all([outletAdmin.settings(),outletAdmin.readiness(),outletAdmin.domains(),outletAdmin.availableDeliveryAreas(),outletAdmin.selectedDeliveryAreas(),outletAdmin.pricingRules(),outletAdmin.discountTiers(),outletAdmin.billing(),outletAdmin.mealPlans(),outletAdmin.subscriptionPlans()]);setData(s);setReadiness(r);setDomains(ds||[]);setAreas(a||[]);setSelectedAreas((ar||[]).map(x=>x.cityAreaId));setPricing(p||[]);setTiers(t||[]);setBilling(b);setMealPlans(mp||[]);setSaasPlans(sp||[]);setPlanChoice(b?.saasPlanId||'');setCycle(b?.billingCycle||'Monthly');setDeliveryDays((s?.deliveryDays||'').split(',').map(x=>x.trim()).filter(Boolean));setCoverageMode(s?.deliveryCoverageMode||'Radius');setServiceRadiusKm(s?.serviceRadiusKm??20);setTax({restaurantGstRate:s?.restaurantGstRate??5,restaurantGstMode:s?.restaurantGstMode||'Exclusive'});setBranding({brandName:s?.branding?.brandName||s?.outletName||'',tagline:s?.branding?.tagline||'',logoUrl:s?.branding?.logoUrl||'',heroImageUrl:s?.branding?.heroImageUrl||'',faviconUrl:s?.branding?.faviconUrl||'',primaryColor:s?.branding?.primaryColor||'#14532d',secondaryColor:s?.branding?.secondaryColor||'#166534',healthHighlights:(s?.branding?.healthHighlights||[]).join(', '),about:s?.branding?.about||'',footerText:s?.branding?.footerText||'',fontFamily:s?.branding?.fontFamily||'Inter',themeStyle:s?.branding?.themeStyle||'Fresh',buttonStyle:s?.branding?.buttonStyle||'Rounded',cardStyle:s?.branding?.cardStyle||'Soft'})}catch(e){setError(e.message||'Unable to load outlet settings.')}finally{setSaving(false)}};
 useEffect(()=>{load()},[]);

 const verifyDomain=async id=>{
   try{
     setSaving(true);setError('');
     const x=await outletAdmin.verifyDomain(id,false);
     setDomains(d=>d.map(v=>v.id===x.id?x:v));
     setToast(x?.status==='Verified'||x?.status==='Active'?'DNS verification confirmed — awaiting/complete platform activation':'DNS verification is not complete yet');
   }catch(e){setError(e.message||'Unable to check domain verification')}finally{setSaving(false)}
 };
 const saveBranding=async e=>{e.preventDefault();try{setSaving(true);const x=await outletAdmin.updateBranding(branding);setBranding({brandName:x?.brandName||'',tagline:x?.tagline||'',logoUrl:x?.logoUrl||'',heroImageUrl:x?.heroImageUrl||'',faviconUrl:x?.faviconUrl||'',primaryColor:x?.primaryColor||'#14532d',secondaryColor:x?.secondaryColor||'#166534',healthHighlights:(x?.healthHighlights||[]).join(', '),about:x?.about||'',footerText:x?.footerText||'',fontFamily:x?.fontFamily||'Inter',themeStyle:x?.themeStyle||'Fresh',buttonStyle:x?.buttonStyle||'Rounded',cardStyle:x?.cardStyle||'Soft'});setData(d=>({...d,branding:x}));setToast('Branding saved')}catch(x){setError(x.message||'Unable to save branding')}finally{setSaving(false)}};
 const requestDomain=async e=>{
   e.preventDefault();
   const hostname=domainForm.hostname.trim();
   if(!hostname)return;
   try{
     setSaving(true);setError('');
     const x=await outletAdmin.requestDomain(hostname,domainForm.isPrimary);
     setDomains(d=>[x,...d.filter(v=>v.id!==x.id)]);
     setDomainForm({hostname:'',isPrimary:false});
     setToast(x?.status==='Active'?'Domain is already active':'Custom domain requested — waiting for Super Admin verification');
   }catch(x){setError(x.message||'Unable to request custom domain')}finally{setSaving(false)}
 };
 const uploadBranding=async(assetType,file)=>{if(!file)return;try{setBrandingUploading(assetType);const x=await outletAdmin.uploadBrandingAsset(assetType,file);setBranding(b=>({...b,logoUrl:x?.logoUrl||b.logoUrl,heroImageUrl:x?.heroImageUrl||b.heroImageUrl,faviconUrl:x?.faviconUrl||b.faviconUrl}));setData(d=>({...d,branding:x}));setToast((assetType==='hero'?'Hero image':assetType==='favicon'?'Favicon':'Logo')+' uploaded')}catch(x){setError(x.message||'Unable to upload branding asset')}finally{setBrandingUploading('')}};
 const saveDays=async()=>{try{setSaving(true);const x=await outletAdmin.updateDeliveryDays(deliveryDays.join(','),coverageMode,Number(serviceRadiusKm));setData(x);setReadiness(x?.readiness);setCoverageMode(x?.deliveryCoverageMode||coverageMode);setServiceRadiusKm(x?.serviceRadiusKm??serviceRadiusKm);setToast('Delivery schedule and coverage saved')}catch(e){setError(e.message||'Unable to save delivery coverage')}finally{setSaving(false)}};
 const saveAreas=async()=>{try{setSaving(true);await outletAdmin.saveDeliveryAreas(selectedAreas);await load();setToast('Service areas saved')}catch(e){setError(e.message||'Unable to save service areas')}finally{setSaving(false)}};
 const addPricing=async e=>{e.preventDefault();try{await outletAdmin.addPricingRule({maxDistanceKm:Number(priceForm.maxDistanceKm),fee:Number(priceForm.fee)});setPriceForm({maxDistanceKm:'',fee:''});await load();setToast('Delivery pricing added')}catch(x){setError(x.message||'Unable to add pricing')}};
 const saveTier=async e=>{e.preventDefault();try{const p={minMeals:Number(tierForm.minMeals),maxMeals:tierForm.maxMeals===''?null:Number(tierForm.maxMeals),oneWeekPercent:Number(tierForm.oneWeekPercent),twoWeeksPercent:Number(tierForm.twoWeeksPercent),oneMonthPercent:Number(tierForm.oneMonthPercent),isActive:true};if(editTier)await outletAdmin.updateDiscountTier(editTier.id,p);else await outletAdmin.addDiscountTier(p);setEditTier(null);setTierForm({minMeals:1,maxMeals:9,oneWeekPercent:0,twoWeeksPercent:0,oneMonthPercent:0});await load();setToast('Discount tier saved')}catch(x){setError(x.message||'Unable to save discount tier')}};
 const removeTier=async t=>{try{await outletAdmin.deleteDiscountTier(t.id);await load();setToast('Discount tier removed')}catch(e){setError(e.message||'Unable to remove discount tier')}};
 const saveTax=async e=>{e.preventDefault();try{await outletAdmin.updateTaxSettings({restaurantGstRate:Number(tax.restaurantGstRate),restaurantGstMode:tax.restaurantGstMode});await load();setToast('Tax settings saved')}catch(x){setError(x.message||'Unable to save tax settings')}};
 const createMealPlan=async e=>{e.preventDefault();try{await outletAdmin.createMealPlan({name:mealPlanForm.name,frequency:mealPlanForm.frequency,mealsPerDay:Number(mealPlanForm.mealsPerDay),price:Number(mealPlanForm.price),description:mealPlanForm.description});setMealPlanForm({name:'',frequency:'Weekly',mealsPerDay:1,mealsPerWeek:7,price:0,currency:'INR',description:''});await load();setToast('Meal plan created')}catch(x){setError(x.message||'Unable to create meal plan')}};
 const changePlan=async e=>{e.preventDefault();try{setSaving(true);await outletAdmin.changeSubscription(planChoice,cycle);await load();setToast('HealthApp billing plan updated')}catch(x){setError(x.message||'Unable to update subscription')}finally{setSaving(false)}};
 const goLive=async()=>{try{setSaving(true);setConfirmLive(false);const x=await outletAdmin.goLive();setReadiness(x);setData(d=>({...d,readiness:x}));setToast('Outlet is now LIVE for customers')}catch(e){setError(e.message||'Unable to make outlet live')}finally{setSaving(false)}};

 if(saving&& !data)return <div className="settingsLoading"><div className="settingsSpinner">⚙</div><h2>Loading outlet settings…</h2></div>;
 return <div className="settingsPage">
  <div className="settingsHero"><div className="settingsHeroCopy"><span className="eyebrow">OUTLET SETTINGS</span><h1>{data?.outletName||'Outlet'} configuration</h1><p>Configure the customer experience, operations and launch settings for this outlet.</p><div className="settingsHeroActions"><button type="button" className="secondary" onClick={()=>setPreviewOpen(true)} disabled={!data?.outletSlug}>↗ Preview customer site</button>{getCustomerPreviewUrl()&&<a className="linkBtn settingsLiveLink" href={getCustomerPreviewUrl()} target="_blank" rel="noreferrer">Open live site ↗</a>}</div></div><div className={'settingsStatus '+(readiness?.isLive?'live':'active')}><span>{readiness?.isLive?'LIVE':'ACTIVATED'}</span><b>{readiness?.isLive?'Customer facing':'Setup in progress'}</b><small>{readiness?.message}</small></div></div>
  <div className="settingsLayout"><aside className="settingsMenu">{SECTIONS.map(x=><button key={x[0]} className={section===x[0]?'settingsMenuItem active':'settingsMenuItem'} onClick={()=>setSection(x[0])}><span>{x[1]}</span>{x[2]}</button>)}</aside>
  <div className="settingsContent">
   {error&&<div className="statusBanner error"><span><b>⚠ Something needs attention</b>{error}</span><button onClick={()=>setError('')}>×</button></div>}{toast&&<div className="settingsToast">✓ {toast}</div>}

   {section==='overview'&&<><section className="settingsSection introSection"><div><span className="eyebrow">GO-LIVE READINESS</span><h2>Complete your operating setup</h2><p>Use the checklist below to prepare the outlet after Super Admin activation.</p></div><div className="readinessScore"><b>{readiness?.items?.filter(x=>x.isComplete).length||0}/{readiness?.items?.length||0}</b><span>checks complete</span></div></section><div className="readinessGrid">{(readiness?.items||[]).map(item=><article className={item.isComplete?'readinessCard complete':'readinessCard'} key={item.key}><div className="readinessIcon">{item.isComplete?'✓':'!'}</div><div><b>{item.title}</b><p>{item.description}</p><small>{item.isComplete?item.currentCount+' configured':item.currentCount+' of '+item.requiredCount+' required'}</small></div>{item.isComplete?<span className="readinessDone">Ready</span>:<button className="linkBtn" onClick={()=>{if(item.configureSection==='recipes'||item.configureSection==='menu'||item.configureSection==='drivers')onNavigate(item.configureSection==='drivers'?'routes':item.configureSection);else if(item.configureSection==='meal-plans')setSection('meal-plans');else if(item.configureSection==='delivery-areas')setSection('areas');else if(item.configureSection==='pricing')setSection('pricing');else if(item.configureSection==='delivery-days')setSection('delivery');else if(item.configureSection==='tax')setSection('tax')}}>Configure →</button>}</article>)}</div><section className="goLiveCard"><div><span className="eyebrow">CUSTOMER VISIBILITY</span><h3>{readiness?.isLive?'Your outlet is live':'Not live yet'}</h3><p>{readiness?.isLive?'Customers can discover your outlet and subscribe.':'Activation is an internal state. Go live only after recipes, delivery, kitchen and commercial settings are ready.'}</p></div><button className="primary big" disabled={!readiness?.canGoLive||readiness?.isLive||saving} onClick={()=>setConfirmLive(true)}>{readiness?.isLive?'Outlet is live':saving?'Working…':'Make outlet live →'}</button></section></>}

   {section==='branding'&&<section className="settingsSection">
    <div className="settingsSectionHead"><div><span className="eyebrow">OUTLET BRANDING</span><h2>Design the customer experience</h2><p>Set your visual identity once. These choices control the outlet customer landing page on mobile and desktop.</p></div><button className="primary" onClick={saveBranding} disabled={saving}>Save branding</button></div>
    <form className="settingsPlanForm brandingConfigForm" onSubmit={saveBranding}>
      <div className="brandingFieldGroup"><div className="brandingFieldLabel"><b>Brand identity</b><span>Name, message and supporting copy.</span></div><div className="brandingFieldGrid">
        <label className="field"><span>Brand name</span><input value={branding.brandName} onChange={e=>setBranding({...branding,brandName:e.target.value})} maxLength="200" required/></label>
        <label className="field"><span>Tagline</span><input value={branding.tagline} onChange={e=>setBranding({...branding,tagline:e.target.value})} maxLength="300" placeholder="Fresh meals, made for your routine"/></label>
        <label className="field span2"><span>About</span><textarea rows="3" value={branding.about} onChange={e=>setBranding({...branding,about:e.target.value})} maxLength="4000" placeholder="Tell customers what makes your outlet special."/></label>
        <label className="field span2"><span>Highlights</span><input value={branding.healthHighlights} onChange={e=>setBranding({...branding,healthHighlights:e.target.value})} maxLength="2000" placeholder="Fresh ingredients, High protein, Chef prepared"/></label>
        <label className="field span2"><span>Footer text</span><input value={branding.footerText} onChange={e=>setBranding({...branding,footerText:e.target.value})} maxLength="1000" placeholder="Fresh meals. Better routines."/></label>
      </div></div>
      <div className="brandingFieldGroup"><div className="brandingFieldLabel"><b>Colours</b><span>Keep primary for actions and accents; secondary supports surfaces and highlights.</span></div><div className="brandingFieldGrid">
        <label className="colorField"><span>Primary colour</span><div><input type="color" value={branding.primaryColor} onChange={e=>setBranding({...branding,primaryColor:e.target.value})}/><code>{branding.primaryColor}</code></div></label>
        <label className="colorField"><span>Secondary colour</span><div><input type="color" value={branding.secondaryColor} onChange={e=>setBranding({...branding,secondaryColor:e.target.value})}/><code>{branding.secondaryColor}</code></div></label>
      </div></div>
      <div className="brandingFieldGroup"><div className="brandingFieldLabel"><b>Typography & component style</b><span>These settings create a consistent branded design system instead of styling each page separately.</span></div><div className="brandingFieldGrid">
        <label className="field"><span>Font</span><select value={branding.fontFamily} onChange={e=>setBranding({...branding,fontFamily:e.target.value})}><option>Inter</option><option>Poppins</option><option>DM Sans</option><option>Nunito</option><option>Manrope</option></select></label>
        <label className="field"><span>Visual theme</span><select value={branding.themeStyle} onChange={e=>setBranding({...branding,themeStyle:e.target.value})}><option>Fresh</option><option>Modern</option><option>Premium</option><option>Minimal</option></select></label>
        <label className="field"><span>Button shape</span><select value={branding.buttonStyle} onChange={e=>setBranding({...branding,buttonStyle:e.target.value})}><option>Rounded</option><option>Pill</option><option>Square</option></select></label>
        <label className="field"><span>Card style</span><select value={branding.cardStyle} onChange={e=>setBranding({...branding,cardStyle:e.target.value})}><option>Soft</option><option>Elevated</option><option>Flat</option></select></label>
      </div></div>
      <div className={`brandingLivePreview theme-${String(branding.themeStyle).toLowerCase()} cards-${String(branding.cardStyle).toLowerCase()}`} style={{'--brand-primary':branding.primaryColor,'--brand-secondary':branding.secondaryColor,'--brand-font':branding.fontFamily}}>
        <div className="brandingLivePreviewTop"><span className="brandingPreviewLogo">{branding.brandName?.slice(0,1).toUpperCase()||'F'}</span><div><b>{branding.brandName||'Your outlet'}</b><small>{branding.tagline||'Fresh meals, made for your routine'}</small></div></div>
        <div className="brandingPreviewHero"><div><span>LIVE CUSTOMER STYLE</span><h3>{branding.tagline||'Healthy meals made for your routine.'}</h3><p>{branding.about||'Preview your colours, typography, buttons and cards before customers see them.'}</p><button className={`brandingPreviewButton shape-${String(branding.buttonStyle).toLowerCase()}`}>Build my meal plan →</button></div><div className="brandingPreviewImage">{branding.heroImageUrl?<img src={branding.heroImageUrl} alt=""/>:<span>Hero image</span>}</div></div>
        <div className="brandingPreviewCards"><div>Morning menu</div><div>Afternoon menu</div><div>Fresh delivery</div></div>
      </div>
    </form>
    <div className="settingsDataList">
      <div className="settingsDataRow"><div><b>Logo</b><span>Used in the customer header, preview and outlet branding.</span></div><div className="settingsRowActions">{branding.logoUrl&&<img src={branding.logoUrl} alt="" style={{width:42,height:42,objectFit:'contain',borderRadius:9,border:'1px solid #dfe8e1'}}/>}<label className="secondary">Upload<input type="file" accept=".jpg,.jpeg,.png,.webp" style={{display:'none'}} onChange={e=>uploadBranding('logo',e.target.files?.[0])}/></label></div></div>
      <div className="settingsDataRow"><div><b>Hero image</b><span>Used on the customer landing page.</span></div><div className="settingsRowActions">{branding.heroImageUrl&&<img src={branding.heroImageUrl} alt="" style={{width:72,height:42,objectFit:'cover',borderRadius:9,border:'1px solid #dfe8e1'}}/>}<label className="secondary">Upload<input type="file" accept=".jpg,.jpeg,.png,.webp" style={{display:'none'}} onChange={e=>uploadBranding('hero',e.target.files?.[0])}/></label></div></div>
      <div className="settingsDataRow"><div><b>Favicon</b><span>Browser tab icon for the customer portal.</span></div><div className="settingsRowActions">{branding.faviconUrl&&<img src={branding.faviconUrl} alt="" style={{width:32,height:32,objectFit:'contain',borderRadius:7,border:'1px solid #dfe8e1'}}/>}<label className="secondary">Upload<input type="file" accept=".png,.ico,.jpg,.jpeg,.webp" style={{display:'none'}} onChange={e=>uploadBranding('favicon',e.target.files?.[0])}/></label></div></div>
      {brandingUploading&&<div className="settingsToolbar">Uploading {brandingUploading}…</div>}
    </div>
   </section>}
   {section==='domains'&&<section className="settingsSection">
    <div className="settingsSectionHead">
      <div><span className="eyebrow">CUSTOMER PORTAL DOMAINS</span><h2>Connect your customer website</h2><p>Every outlet gets a HealthApp platform address automatically. You can also request your own domain such as <b>www.fitfood.com</b>.</p></div>
    </div>
    <div className="settingsDataList">
      {domains.map(d=><div className="settingsDataRow" key={d.id||d.hostname}>
        <div>
          <b>{d.hostname}</b>
          <span>{d.type} domain · {d.status}{d.isPrimary?' · Primary':''}</span>
          {d.type==='Custom'&&<><small>Cloudflare: {d.providerStatus||'not checked'} · Validation: {d.providerValidationStatus||'not checked'}{d.providerError?' · '+d.providerError:''}</small>{d.status!=='Active'&&d.verificationName&&d.verificationValue&&<small>DNS {d.verificationRecordType||'TXT'}: <code>{d.verificationName}</code> = <code>{d.verificationValue}</code></small>}</>}
        </div>
        <div className="settingsRowActions">
          {d.type==='Custom'&&<><span className="pill">{d.status}</span>{d.status!=='Active'&&<button type="button" className="secondary" onClick={()=>verifyDomain(d.id)} disabled={saving}>Check DNS</button>}</>}
          {d.type==='Platform'&&<span className="pill">Automatic</span>}
        </div>
      </div>)}
      {!domains.length&&<div className="settingsEmpty">No customer portal domains are configured yet.</div>}
    </div>
    <form className="settingsInlineForm" onSubmit={requestDomain}>
      <label className="field span2"><span>Custom domain</span><input value={domainForm.hostname} onChange={e=>setDomainForm({...domainForm,hostname:e.target.value})} placeholder="www.fitfood.com" maxLength="253" required/></label>
      <label className="check"><input type="checkbox" checked={domainForm.isPrimary} onChange={e=>setDomainForm({...domainForm,isPrimary:e.target.checked})}/> Mark as primary</label>
      <button className="primary" disabled={saving||!domainForm.hostname.trim()}>Request domain</button>
    </form>
    <div className="settingsToolbar"><b>Verification</b><span>Cloudflare Pages checks the domain attachment and DNS validation. After adding the TXT record at your domain provider, use <b>Check DNS</b>. Super Admin activation is still required before the hostname becomes an active HealthApp tenant.</span></div>
   </section>}

   {section==='delivery'&&<section className="settingsSection"><div className="settingsSectionHead"><div><span className="eyebrow">DELIVERY SCHEDULE</span><h2>Choose your delivery days</h2><p>These days drive the weekly menu launch check and customer delivery calendar.</p></div><button className="primary" onClick={saveDays} disabled={saving}>Save days</button></div><div className="dayPicker">{DAYS.map(day=><button type="button" key={day} className={deliveryDays.includes(day)?'dayOption selected':'dayOption'} onClick={()=>setDeliveryDays(x=>x.includes(day)?x.filter(v=>v!==day):[...x,day])}><span>{day.slice(0,3)}</span><b>{day}</b></button>)}</div></section>}

   {section==='areas'&&<section className="settingsSection"><div className="settingsSectionHead"><div><span className="eyebrow">SERVICE AREAS</span><h2>Where will you deliver?</h2><p>Choose a simple delivery radius or select approved areas for tighter coverage.</p></div><button className="primary" onClick={saveDays} disabled={saving}>Save coverage</button></div><div className="coverageModeCards"><button type="button" className={coverageMode==='Radius'?'coverageModeCard selected':'coverageModeCard'} onClick={()=>setCoverageMode('Radius')}><b>📍 Delivery radius</b><span>Best for simple city coverage. Customers inside the circle are serviceable.</span></button><button type="button" className={coverageMode==='Areas'?'coverageModeCard selected':'coverageModeCard'} onClick={()=>setCoverageMode('Areas')}><b>◎ Selected areas</b><span>Choose only the approved city areas configured by HealthApp.</span></button></div>{coverageMode==='Radius'?<><div className="coverageRadiusControls"><label className="field"><span>Radius (km)</span><input type="number" min="1" max="100" step=".5" value={serviceRadiusKm} onChange={e=>setServiceRadiusKm(e.target.value)}/><small>Drag the radius on the map conceptually by changing this value. The outlet pin is the centre.</small></label><div className="radiusQuickChoices">{[5,10,15,20,30].map(k=><button type="button" className={Number(serviceRadiusKm)===k?'active':''} key={k} onClick={()=>setServiceRadiusKm(k)}>{k} km</button>)}</div></div><div className="coverageMapWrap">{data?.latitude||data?.longitude?<MapContainer center={[data.latitude,data.longitude]} zoom={11} scrollWheelZoom className="coverageMap"><TileLayer attribution="&copy; OpenStreetMap contributors" url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png"/><CircleMarker center={[data.latitude,data.longitude]} radius={9}/><Circle center={[data.latitude,data.longitude]} radius={Number(serviceRadiusKm||0)*1000} pathOptions={{fillOpacity:.12,weight:2}}/></MapContainer>:<div className="settingsEmpty">Outlet map coordinates are not available.</div>}</div></>:<><div className="settingsToolbar"><b>{selectedAreas.length}</b> approved areas selected</div><div className="settingsAreaGrid">{areas.map(a=><label className={selectedAreas.includes(a.id)?'settingsArea checked':'settingsArea'} key={a.id}><input type="checkbox" checked={selectedAreas.includes(a.id)} onChange={e=>setSelectedAreas(e.target.checked?[...selectedAreas,a.id]:selectedAreas.filter(x=>x!==a.id))}/><div><b>{a.name}</b><span>{a.city} · {a.pincode}</span></div></label>)}</div></>}</section>}

   {section==='pricing'&&<section className="settingsSection"><div className="settingsSectionHead"><div><span className="eyebrow">DELIVERY PRICING</span><h2>Configure distance-based fees</h2><p>Customers are charged according to the nearest matching distance slab.</p></div></div><form className="settingsInlineForm" onSubmit={addPricing}><label className="field"><span>Up to km</span><input type="number" min="0.1" step=".1" value={priceForm.maxDistanceKm} onChange={e=>setPriceForm({...priceForm,maxDistanceKm:e.target.value})} required/></label><label className="field"><span>Fee (₹)</span><input type="number" min="0" step=".01" value={priceForm.fee} onChange={e=>setPriceForm({...priceForm,fee:e.target.value})} required/></label><button className="primary" disabled={saving}>Add slab</button></form><div className="settingsDataList">{pricing.map(p=><div className="settingsDataRow" key={p.id}><div><b>≤ {p.maxDistanceKm} km</b><span>Delivery fee</span></div><strong>{money(p.fee)}</strong></div>)}{!pricing.length&&<div className="settingsEmpty">Add at least one delivery pricing slab.</div>}</div></section>}

   {section==='discounts'&&<section className="settingsSection"><div className="settingsSectionHead"><div><span className="eyebrow">SUBSCRIPTION DISCOUNTS</span><h2>Configure customer subscription savings</h2><p>Use quantity and duration based discounts to reward committed customers.</p></div></div><form className="settingsDiscountForm" onSubmit={saveTier}><label className="field"><span>Min meals</span><input type="number" min="1" value={tierForm.minMeals} onChange={e=>setTierForm({...tierForm,minMeals:e.target.value})}/></label><label className="field"><span>Max meals</span><input type="number" min="1" value={tierForm.maxMeals} onChange={e=>setTierForm({...tierForm,maxMeals:e.target.value})}/></label><label className="field"><span>1 week %</span><input type="number" min="0" max="100" step=".1" value={tierForm.oneWeekPercent} onChange={e=>setTierForm({...tierForm,oneWeekPercent:e.target.value})}/></label><label className="field"><span>2 weeks %</span><input type="number" min="0" max="100" step=".1" value={tierForm.twoWeeksPercent} onChange={e=>setTierForm({...tierForm,twoWeeksPercent:e.target.value})}/></label><label className="field"><span>1 month %</span><input type="number" min="0" max="100" step=".1" value={tierForm.oneMonthPercent} onChange={e=>setTierForm({...tierForm,oneMonthPercent:e.target.value})}/></label><button className="primary" disabled={saving}>{editTier?'Update tier':'Add tier'}</button></form><div className="settingsDataList">{tiers.map(t=><div className="settingsDataRow" key={t.id}><div><b>{t.minMeals} – {t.maxMeals===null?'∞':t.maxMeals} meals</b><span>1W {t.oneWeekPercent}% · 2W {t.twoWeeksPercent}% · 1M {t.oneMonthPercent}%</span></div><div className="settingsRowActions"><button className="secondary" onClick={()=>{setEditTier(t);setTierForm({...t,maxMeals:t.maxMeals===null?'':t.maxMeals})}}>Edit</button><button className="dangerText" onClick={()=>removeTier(t)}>Delete</button></div></div>)}</div></section>}

   {section==='meal-plans'&&<section className="settingsSection"><div className="settingsSectionHead"><div><span className="eyebrow">CUSTOMER MEAL PLANS</span><h2>Create the plans customers can buy</h2><p>At least one active meal plan is required before going live.</p></div></div><form className="settingsPlanForm" onSubmit={createMealPlan}><label className="field"><span>Plan name</span><input value={mealPlanForm.name} onChange={e=>setMealPlanForm({...mealPlanForm,name:e.target.value})} required/></label><label className="field"><span>Frequency</span><select value={mealPlanForm.frequency} onChange={e=>setMealPlanForm({...mealPlanForm,frequency:e.target.value})}><option>Weekly</option><option>Biweekly</option><option>Monthly</option></select></label><label className="field"><span>Meals / day</span><input type="number" min="1" value={mealPlanForm.mealsPerDay} onChange={e=>setMealPlanForm({...mealPlanForm,mealsPerDay:e.target.value})}/></label><label className="field"><span>Meals / week</span><input type="number" min="1" value={mealPlanForm.mealsPerWeek} onChange={e=>setMealPlanForm({...mealPlanForm,mealsPerWeek:e.target.value})}/></label><label className="field"><span>Price (₹)</span><input type="number" min="0" step=".01" value={mealPlanForm.price} onChange={e=>setMealPlanForm({...mealPlanForm,price:e.target.value})}/></label><label className="field span2"><span>Description</span><textarea rows="2" value={mealPlanForm.description} onChange={e=>setMealPlanForm({...mealPlanForm,description:e.target.value})}/></label><button className="primary" disabled={saving}>Create meal plan</button></form><div className="settingsDataList">{mealPlans.map(p=><div className="settingsDataRow" key={p.id}><div><b>{p.name}</b><span>{p.frequency} · {p.mealsPerDay} meal/day · {p.mealsPerWeek} meal/week</span></div><strong>{money(p.price)}</strong></div>)}</div></section>}

   {section==='tax'&&<section className="settingsSection"><div className="settingsSectionHead"><div><span className="eyebrow">TAX & GST</span><h2>Customer tax treatment</h2><p>Used in customer package quotes and financial reporting.</p></div><button className="primary" onClick={saveTax} disabled={saving}>Save tax settings</button></div><div className="settingsTaxGrid"><label className="field"><span>Restaurant GST %</span><input type="number" min="0" max="100" step=".01" value={tax.restaurantGstRate} onChange={e=>setTax({...tax,restaurantGstRate:e.target.value})}/></label><div className="taxModeCards"><button type="button" className={tax.restaurantGstMode==='Exclusive'?'taxModeCard selected':'taxModeCard'} onClick={()=>setTax({...tax,restaurantGstMode:'Exclusive'})}><b>GST Exclusive</b><span>GST is added at checkout.</span></button><button type="button" className={tax.restaurantGstMode==='Inclusive'?'taxModeCard selected':'taxModeCard'} onClick={()=>setTax({...tax,restaurantGstMode:'Inclusive'})}><b>GST Inclusive</b><span>GST is extracted from the displayed price.</span></button></div></div></section>}

   {section==='legal'&&<section className="settingsSection">
    <div className="settingsSectionHead"><div><span className="eyebrow">LEGAL CENTRE</span><h2>Terms, privacy & customer policies</h2><p>These are draft templates for the outlet agreement and the customer-facing policies. Final text must be reviewed for the outlet's business and applicable jurisdictions before publication.</p></div></div>
    <div className="legalSettingsGrid">
      <article className="legalSettingsCard"><span className="eyebrow">HEALTHAPP → OUTLET</span><h3>SaaS agreement</h3><p>Platform terms, subscription fees, outlet responsibilities, IP, security, suspension, termination and disputes.</p><a className="secondary" href="?legal=saas-terms">Open draft →</a></article>
      <article className="legalSettingsCard"><span className="eyebrow">HEALTHAPP → OUTLET</span><h3>Data Processing Addendum</h3><p>Draft controller/processor terms, security, subprocessors, transfers, deletion and assistance.</p><a className="secondary" href="?legal=dpa">Open draft →</a></article>
      <article className="legalSettingsCard"><span className="eyebrow">PLATFORM USE</span><h3>Acceptable Use & Platform Rules</h3><p>Draft security, account, content, customer-treatment and lawful-use rules for the outlet portal.</p><a className="secondary" href="?legal=acceptable-use">Open draft →</a></article>
      <article className="legalSettingsCard featured"><span className="eyebrow">OUTLET → CUSTOMER</span><h3>Customer terms & policies</h3><p>Use the customer templates as the starting point for cancellation, skip, reschedule, delivery, allergen and payment rules.</p><div className="legalSettingsLinks"><a href={getCustomerLegalUrl('terms')} target="_blank" rel="noreferrer">Customer Terms ↗</a><a href={getCustomerLegalUrl('privacy')} target="_blank" rel="noreferrer">Privacy Policy ↗</a><span>Customer policy templates are currently drafts; persistent outlet-specific configuration will be wired before publication.</span></div></article>
    </div>
    <div className="settingsToolbar legalDraftToolbar"><b>Draft status</b><span>Do not publish these templates as final legal advice. They are designed to become versioned outlet documents after business rules, contact details, local law and data-protection roles are confirmed.</span></div>
   </section>}

   {section==='billing'&&<section className="settingsSection"><div className="settingsSectionHead"><div><span className="eyebrow">HEALTHAPP BILLING</span><h2>Plan & billing</h2><p>Change the outlet's SaaS plan here. Billing remains part of settings rather than the operating navigation.</p></div></div>{billing&&<div className="currentBilling"><span>CURRENT PLAN</span><b>{billing.planName}</b><strong>{money(billing.subscriptionFee)} <small>/ {billing.billingCycle}</small></strong><p>{billing.activeCustomers} active customers · {billing.transactionFeePercent}% transaction fee</p></div>}<form className="billingSettingsForm" onSubmit={changePlan}><label className="field"><span>HealthApp plan</span><select value={planChoice} onChange={e=>setPlanChoice(e.target.value)}><option value="">Select a plan</option>{saasPlans.map(p=><option value={p.id} key={p.id}>{p.name} · {money(cycle==='Annual'?p.annualFee:p.monthlyFee)} / {cycle.toLowerCase()}</option>)}</select></label><div className="cycleToggle"><button type="button" className={cycle==='Monthly'?'active':''} onClick={()=>setCycle('Monthly')}>Monthly</button><button type="button" className={cycle==='Annual'?'active':''} onClick={()=>setCycle('Annual')}>Annual</button></div><button className="primary" disabled={!planChoice||saving}>Save billing plan</button></form></section>}
  </div></div>
  {previewOpen&&<div className="settingsPreviewBackdrop" onMouseDown={e=>e.target===e.currentTarget&&setPreviewOpen(false)}><div className="settingsPreviewModal"><div className="settingsPreviewHeader"><div><span className="eyebrow">CUSTOMER EXPERIENCE PREVIEW</span><h2>{data?.outletName||'Outlet'}</h2><p>Live preview of the customer landing page using this outlet's current branding and menu configuration.</p></div><button className="settingsPreviewClose" onClick={()=>setPreviewOpen(false)}>×</button></div><div className="settingsPreviewToolbar"><span>Preview mode · Changes appear after the customer page reloads.</span>{getCustomerPreviewUrl()&&<a className="secondary smallBtn" href={getCustomerPreviewUrl()} target="_blank" rel="noreferrer">Open in new tab ↗</a>}</div><div className="settingsPreviewFrameWrap">{getCustomerPreviewUrl()?<iframe title="Customer experience preview" src={getCustomerPreviewUrl()} className="settingsPreviewFrame"/>:<div className="settingsPreviewEmpty">Customer portal preview URL is not configured yet.</div>}</div></div></div>}
  {confirmLive&&<div className="settingsConfirmBackdrop"><div className="settingsConfirm"><span className="settingsConfirmIcon">✓</span><h3>Make this outlet live?</h3><p>This will publish the outlet to the customer marketplace. You can do this only after the required launch checks are complete.</p><div><button className="secondary" onClick={()=>setConfirmLive(false)}>Not yet</button><button className="primary" onClick={goLive}>Yes, make it live</button></div></div></div>}
 </div>;
}
