import React,{useEffect,useState}from'react';
import{money,outletAdmin,CUSTOMER_URL}from'@healthapp/shared';
import{MapContainer,TileLayer,CircleMarker,Circle}from'react-leaflet';
import'leaflet/dist/leaflet.css';

const DAYS=['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday'];
const SECTIONS=[['overview','⚡','Launch checklist'],['branding','✦','Branding'],['domains','⌁','Domains'],['delivery','⌖','Delivery schedule'],['areas','◎','Service coverage'],['pricing','₹','Delivery pricing'],['discounts','%','Subscription discounts'],['meal-plans','▣','Meal plans'],['tax','▤','Tax & GST'],['legal','§','Legal & policies'],['billing','▣','HealthApp billing']];

export default function OutletSettings({onNavigate}){
 const[section,setSection]=useState('overview');
 const[data,setData]=useState(null),[readiness,setReadiness]=useState(null),[domains,setDomains]=useState([]),[areas,setAreas]=useState([]),[selectedAreas,setSelectedAreas]=useState([]),[pricing,setPricing]=useState([]),[tiers,setTiers]=useState([]),[mealPlans,setMealPlans]=useState([]),[saasPlans,setSaasPlans]=useState([]),[billing,setBilling]=useState(null);
 const[deliveryDays,setDeliveryDays]=useState([]),[coverageMode,setCoverageMode]=useState('Radius'),[serviceRadiusKm,setServiceRadiusKm]=useState(20),[priceForm,setPriceForm]=useState({maxDistanceKm:'',fee:''}),[tierForm,setTierForm]=useState({minMeals:1,maxMeals:9,oneWeekPercent:0,twoWeeksPercent:0,oneMonthPercent:0}),[editTier,setEditTier]=useState(null),[mealPlanForm,setMealPlanForm]=useState({name:'',frequency:'Weekly',mealsPerDay:1,mealsPerWeek:7,price:0,currency:'INR',description:'',isPreplanned:false,availableCity:'',durationDays:7}),[packageSettings,setPackageSettings]=useState({customPackagePricingMode:'Calculated',showPackagePriceToCustomer:true,showMealPriceToCustomer:true,showDeliveryFeeToCustomer:true});
 const[domainForm,setDomainForm]=useState({hostname:'',isPrimary:false}),[planChoice,setPlanChoice]=useState(''),[cycle,setCycle]=useState('Monthly'),[tax,setTax]=useState({restaurantGstRate:5,restaurantGstMode:'Exclusive'}),[legal,setLegal]=useState({customerTermsAndConditions:'',customerPrivacyPolicy:'',cancellationRefundPolicy:'',mealSkipReschedulePolicy:'',deliveryPolicy:'',allergenDietaryDisclaimer:'',paymentPricingPromotionalTerms:'',legalVersion:'1.0',legalEffectiveDateUtc:'',legalPoliciesPublished:false,publishedVersionId:'',publishedVersion:'',publishedEffectiveDateUtc:'',versionHistory:[]}),[branding,setBranding]=useState({brandName:'',tagline:'',logoUrl:'',heroImageUrl:'',faviconUrl:'',primaryColor:'#14532d',secondaryColor:'#166534',healthHighlights:'',about:'',footerText:'',fontFamily:'Inter',themeStyle:'Fresh',buttonStyle:'Rounded',cardStyle:'Soft'}),[brandingUploading,setBrandingUploading]=useState(''),[saving,setSaving]=useState(false),[error,setError]=useState(''),[toast,setToast]=useState(''),[confirmLive,setConfirmLive]=useState(false),[previewOpen,setPreviewOpen]=useState(false);

 const getCustomerPreviewUrl=()=>{const custom=[...domains].reverse().find(d=>d.type==='Custom'&&String(d.status).toLowerCase()==='active'&&d.isPrimary)?.hostname;const platform=domains.find(d=>d.type==='Platform'&&d.hostname)?.hostname;const host=window.location.hostname;const isLocal=host==='localhost'||host==='127.0.0.1'||host==='::1';const base=custom?('https://'+custom):(platform&&!isLocal?'https://'+platform:CUSTOMER_URL.replace(/\/$/,''));if(!base)return '';const separator=base.includes('?')?'&':'?';const slug=data?.outletSlug||'';return slug?base+separator+'outlet='+encodeURIComponent(slug):base;};
 const getCustomerLegalUrl=id=>{const base=getCustomerPreviewUrl();if(!base)return '';return base+(base.includes('?')?'&':'?')+'legal='+encodeURIComponent(id);};
 const load=async()=>{try{setSaving(true);setError('');const[s,r,ds,a,ar,p,t,b,mp,sp]=await Promise.all([outletAdmin.settings(),outletAdmin.readiness(),outletAdmin.domains(),outletAdmin.availableDeliveryAreas(),outletAdmin.selectedDeliveryAreas(),outletAdmin.pricingRules(),outletAdmin.discountTiers(),outletAdmin.billing(),outletAdmin.mealPlans(),outletAdmin.subscriptionPlans()]);setData(s);setPackageSettings({customPackagePricingMode:s?.customPackagePricingMode||'Calculated',showPackagePriceToCustomer:s?.showPackagePriceToCustomer!==false,showMealPriceToCustomer:s?.showMealPriceToCustomer!==false,showDeliveryFeeToCustomer:s?.showDeliveryFeeToCustomer!==false});setReadiness(r);setDomains(ds||[]);setAreas(a||[]);setSelectedAreas((ar||[]).map(x=>x.cityAreaId));setPricing(p||[]);setTiers(t||[]);setBilling(b);setMealPlans(mp||[]);setSaasPlans(sp||[]);setPlanChoice(b?.saasPlanId||'');setCycle(b?.billingCycle||'Monthly');setDeliveryDays((s?.deliveryDays||'').split(',').map(x=>x.trim()).filter(Boolean));setCoverageMode(s?.deliveryCoverageMode||'Radius');setServiceRadiusKm(s?.serviceRadiusKm??20);setTax({restaurantGstRate:s?.restaurantGstRate??5,restaurantGstMode:s?.restaurantGstMode||'Exclusive'});setBranding({brandName:s?.branding?.brandName||s?.outletName||'',tagline:s?.branding?.tagline||'',logoUrl:s?.branding?.logoUrl||'',heroImageUrl:s?.branding?.heroImageUrl||'',faviconUrl:s?.branding?.faviconUrl||'',primaryColor:s?.branding?.primaryColor||'#14532d',secondaryColor:s?.branding?.secondaryColor||'#166534',healthHighlights:(s?.branding?.healthHighlights||[]).join(', '),about:s?.branding?.about||'',footerText:s?.branding?.footerText||'',fontFamily:s?.branding?.fontFamily||'Inter',themeStyle:s?.branding?.themeStyle||'Fresh',buttonStyle:s?.branding?.buttonStyle||'Rounded',cardStyle:s?.branding?.cardStyle||'Soft'});const lp=await outletAdmin.legal();setLegal({customerTermsAndConditions:lp?.customerTermsAndConditions||'',customerPrivacyPolicy:lp?.customerPrivacyPolicy||'',cancellationRefundPolicy:lp?.cancellationRefundPolicy||'',mealSkipReschedulePolicy:lp?.mealSkipReschedulePolicy||'',deliveryPolicy:lp?.deliveryPolicy||'',allergenDietaryDisclaimer:lp?.allergenDietaryDisclaimer||'',paymentPricingPromotionalTerms:lp?.paymentPricingPromotionalTerms||'',legalVersion:lp?.legalVersion||'1.0',legalEffectiveDateUtc:lp?.legalEffectiveDateUtc?String(lp.legalEffectiveDateUtc).slice(0,10):'',legalPoliciesPublished:Boolean(lp?.legalPoliciesPublished),publishedVersionId:lp?.publishedVersionId||'',publishedVersion:lp?.publishedVersion||'',publishedEffectiveDateUtc:lp?.publishedEffectiveDateUtc?String(lp.publishedEffectiveDateUtc).slice(0,10):'',versionHistory:lp?.versionHistory||[]});}catch(e){setError(e.message||'Unable to load outlet settings.')}finally{setSaving(false)}};
 useEffect(()=>{load()},[]);

 const verifyDomain=async id=>{
   try{
     setSaving(true);setError('');
     const x=await outletAdmin.verifyDomain(id,false);
     setDomains(d=>d.map(v=>v.id===x.id?x:v));
     setToast(x?.status==='Verified'||x?.status==='Active'?'DNS verification confirmed — awaiting/complete platform activation':'DNS verification is not complete yet');
   }catch(e){setError(e.message||'Unable to check domain verification')}finally{setSaving(false)}
 };
 const saveBranding=async e=>{e.preventDefault();try{setSaving(true);const x=await outletAdmin.updateBranding(branding);setBranding({brandName:x?.brandName||'',tagline:x?.tagline||'',logoUrl:x?.logoUrl||'',heroImageUrl:x?.heroImageUrl||'',faviconUrl:x?.faviconUrl||'',primaryColor:x?.primaryColor||'#14532d',secondaryColor:x?.secondaryColor||'#166534',healthHighlights:(x?.healthHighlights||[]).join(', '),about:x?.about||'',footerText:x?.footerText||'',fontFamily:x?.fontFamily||'Inter',themeStyle:x?.themeStyle||'Fresh',buttonStyle:x?.buttonStyle||'Rounded',cardStyle:x?.cardStyle||'Soft'});setData(d=>({...d,branding:x}));setToast('Branding saved')}catch(x){setError(x.message||'Unable to save branding')}finally{setSaving(false)}};
 const requestDomain=async e=>{
   e.preventDefault();
   const hostname=domainForm.hostname.trim();
   if(!hostname)return;
   try{
     setSaving(true);setError('');
     const x=await outletAdmin.requestDomain(hostname,domainForm.isPrimary);
     setDomains(d=>[x,...d.filter(v=>v.id!==x.id)]);
     setDomainForm({hostname:'',isPrimary:false});
     setToast(x?.status==='Active'?'Domain is already active':'Custom domain requested — waiting for Super Admin verification');
   }catch(x){setError(x.message||'Unable to request custom domain')}finally{setSaving(false)}
 };
 const uploadBranding=async(assetType,file)=>{if(!file)return;try{setBrandingUploading(assetType);const x=await outletAdmin.uploadBrandingAsset(assetType,file);setBranding(b=>({...b,logoUrl:x?.logoUrl||b.logoUrl,heroImageUrl:x?.heroImageUrl||b.heroImageUrl,faviconUrl:x?.faviconUrl||b.faviconUrl}));setData(d=>({...d,branding:x}));setToast((assetType==='hero'?'Hero image':assetType==='favicon'?'Favicon':'Logo')+' uploaded')}catch(x){setError(x.message||'Unable to upload branding asset')}finally{setBrandingUploading('')}};
 const saveDays=async()=>{try{setSaving(true);const x=await outletAdmin.updateDeliveryDays(deliveryDays.join(','),coverageMode,Number(serviceRadiusKm));setData(x);setReadiness(x?.readiness);setCoverageMode(x?.deliveryCoverageMode||coverageMode);setServiceRadiusKm(x?.serviceRadiusKm??serviceRadiusKm);setToast('Delivery schedule and coverage saved')}catch(e){setError(e.message||'Unable to save delivery coverage')}finally{setSaving(false)}};
 const saveAreas=async()=>{try{setSaving(true);await outletAdmin.saveDeliveryAreas(selectedAreas);await load();setToast('Service areas saved')}catch(e){setError(e.message||'Unable to save service areas')}finally{setSaving(false)}};
 const addPricing=async e=>{e.preventDefault();try{await outletAdmin.addPricingRule({maxDistanceKm:Number(priceForm.maxDistanceKm),fee:Number(priceForm.fee)});setPriceForm({maxDistanceKm:'',fee:''});await load();setToast('Delivery pricing added')}catch(x){setError(x.message||'Unable to add pricing')}};
 const saveTier=async e=>{e.preventDefault();try{const p={minMeals:Number(tierForm.minMeals),maxMeals:tierForm.maxMeals===''?null:Number(tierForm.maxMeals),oneWeekPercent:Number(tierForm.oneWeekPercent),twoWeeksPercent:Number(tierForm.twoWeeksPercent),oneMonthPercent:Number(tierForm.oneMonthPercent),isActive:true};if(editTier)await outletAdmin.updateDiscountTier(editTier.id,p);else await outletAdmin.addDiscountTier(p);setEditTier(null);setTierForm({minMeals:1,maxMeals:9,oneWeekPercent:0,twoWeeksPercent:0,oneMonthPercent:0});await load();setToast('Discount tier saved')}catch(x){setError(x.message||'Unable to save discount tier')}};
 const removeTier=async t=>{try{await outletAdmin.deleteDiscountTier(t.id);await load();setToast('Discount tier removed')}catch(e){setError(e.message||'Unable to remove discount tier')}};
 const savePackageSettings=async e=>{e?.preventDefault?.();try{setSaving(true);await outletAdmin.updatePackageSettings(packageSettings);await load();setToast('Customer package settings saved')}catch(x){setError(x.message||'Unable to save package settings')}finally{setSaving(false)}};
 const saveTax=async e=>{e.preventDefault();try{await outletAdmin.updateTaxSettings({restaurantGstRate:Number(tax.restaurantGstRate),restaurantGstMode:tax.restaurantGstMode});await load();setToast('Tax settings saved')}catch(x){setError(x.message||'Unable to save tax settings')}};
 const createMealPlan=async e=>{e.preventDefault();try{if(mealPlanForm.isPreplanned&&Number(mealPlanForm.price)<=0)throw new Error('A preplanned package requires a fixed price greater than zero.');await outletAdmin.createMealPlan({name:mealPlanForm.name,frequency:mealPlanForm.frequency,mealsPerDay:Number(mealPlanForm.mealsPerDay),price:Number(mealPlanForm.price),description:mealPlanForm.description,isPreplanned:Boolean(mealPlanForm.isPreplanned),availableCity:mealPlanForm.isPreplanned?(mealPlanForm.availableCity||data?.city||''): '',durationDays:Number(mealPlanForm.durationDays||7)});setMealPlanForm({name:'',frequency:'Weekly',mealsPerDay:1,mealsPerWeek:7,price:0,currency:'INR',description:'',isPreplanned:false,availableCity:data?.city||'',durationDays:7});await load();setToast('Meal plan created')}catch(x){setError(x.message||'Unable to create meal plan')}};
 const changePlan=async e=>{e.preventDefault();try{setSaving(true);await outletAdmin.changeSubscription(planChoice,cycle);await load();setToast('HealthApp billing plan updated')}catch(x){setError(x.message||'Unable to update subscription')}finally{setSaving(false)}};
 const goLive=async()=>{try{setSaving(true);setConfirmLive(false);const x=await outletAdmin.goLive();setReadiness(x);setData(d=>({...d,readiness:x}));setToast('Outlet is now LIVE for customers')}catch(e){setError(e.message||'Unable to make outlet live')}finally{setSaving(false)}};

 const saveLegal=async(e,publish=false)=>{if(e)e.preventDefault();try{setSaving(true);const payload={...legal,legalPoliciesPublished:Boolean(publish),legalEffectiveDateUtc:legal.legalEffectiveDateUtc||null};const x=await outletAdmin.updateLegal(payload);setLegal({customerTermsAndConditions:x?.customerTermsAndConditions||'',customerPrivacyPolicy:x?.customerPrivacyPolicy||'',cancellationRefundPolicy:x?.cancellationRefundPolicy||'',mealSkipReschedulePolicy:x?.mealSkipReschedulePolicy||'',deliveryPolicy:x?.deliveryPolicy||'',allergenDietaryDisclaimer:x?.allergenDietaryDisclaimer||'',paymentPricingPromotionalTerms:x?.paymentPricingPromotionalTerms||'',legalVersion:x?.legalVersion||'1.0',legalEffectiveDateUtc:x?.legalEffectiveDateUtc?String(x.legalEffectiveDateUtc).slice(0,10):'',legalPoliciesPublished:Boolean(x?.legalPoliciesPublished),publishedVersionId:x?.publishedVersionId||'',publishedVersion:x?.publishedVersion||'',publishedEffectiveDateUtc:x?.publishedEffectiveDateUtc?String(x.publishedEffectiveDateUtc).slice(0,10):'',versionHistory:x?.versionHistory||[]});setToast(publish?'Customer legal policies published':'Customer legal policy draft saved')}catch(e){setError(e.message||'Unable to save legal policies')}finally{setSaving(false)}};
 if(saving&& !data)return <div className="settingsLoading"><div className="settingsSpinner">⚙</div><h2>Loading outlet settings…</h2></div>;
 return <div className="settingsPage">
  <div className="settingsHero"><div className="settingsHeroCopy"><span className="eyebrow">OUTLET SETTINGS</span><h1>{data?.outletName||'Outlet'} configuration</h1><p>Configure the customer experience, operations and launch settings for this outlet.</p><div className="settingsHeroActions"><button type="button" className="secondary" onClick={()=>setPreviewOpen(true)} disabled={!data?.outletSlug}>↗ Preview customer site</button>{getCustomerPreviewUrl()&&<a className="linkBtn settingsLiveLink" href={getCustomerPreviewUrl()} target="_blank" rel="noreferrer">Open live site ↗</a>}</div></div><div className={'settingsStatus '+(readiness?.isLive?'live':'active')}><span>{readiness?.isLive?'LIVE':'ACTIVATED'}</span><b>{readiness?.isLive?'Customer facing':'Setup in progress'}</b><small>{readiness?.message}</small></div></div>
  <div className="settingsLayout"><aside className="settingsMenu">{SECTIONS.map(x=><button key={x[0]} className={section===x[0]?'settingsMenuItem active':'settingsMenuItem'} onClick={()=>setSection(x[0])}><span>{x[1]}</span>{x[2]}</button>)}</aside>
  <div className="settingsContent">
   {error&&<div className="statusBanner error"><span><b>⚠ Something needs attention</b>{error}</span><button onClick={()=>setError('')}>×</button></div>}{toast&&<div className="settingsToast">✓ {toast}</div>}

   {section==='overview'&&<><section className="settingsSection introSection"><div><span className="eyebrow">GO-LIVE READINESS</span><h2>Complete your operating setup</h2><p>Use the checklist below to prepare the outlet after Super Admin activation.</p></div><div className="readinessScore"><b>{readiness?.items?.filter(x=>x.isComplete).length||0}/{readiness?.items?.length||0}</b><span>checks complete</span></div></section><div className="readinessGrid">{(readiness?.items||[]).map(item=><article className={item.isComplete?'readinessCard complete':'readinessCard'} key={item.key}><div className="readinessIcon">{item.isComplete?'✓':'!'}</div><div><b>{item.title}</b><p>{item.description}</p><small>{item.isComplete?item.currentCount+' configured':item.currentCount+' of '+item.requiredCount+' required'}</small></div>{item.isComplete?<span className="readinessDone">Ready</span>:<button className="linkBtn" onClick={()=>{if(item.configureSection==='recipes'||item.configureSection==='menu'||item.configureSection==='drivers')onNavigate(item.configureSection==='drivers'?'routes':item.configureSection);else if(item.configureSection==='meal-plans')setSection('meal-plans');else if(item.configureSection==='delivery-areas')setSection('areas');else if(item.configureSection==='pricing')setSection('pricing');else if(item.configureSection==='delivery-days')setSection('delivery');else if(item.configureSection==='tax')setSection('tax');else if(item.configureSection==='legal')setSection('legal')}}>Configure →</button>}</article>)}</div><section className="goLiveCard"><div><span className="eyebrow">CUSTOMER VISIBILITY</span><h3>{readiness?.isLive?'Your outlet is live':'Not live yet'}</h3><p>{readiness?.isLive?'Customers can discover your outlet and subscribe.':'Activation is an internal state. Go live only after recipes, delivery, kitchen and commercial settings are ready.'}</p></div><button className="primary big" disabled={!readiness?.canGoLive||readiness?.isLive||saving} onClick={()=>setConfirmLive(true)}>{readiness?.isLive?'Outlet is live':saving?'Working…':'Make outlet live →'}</button></section></>}

   {section==='branding'&&<section className="settingsSection">
    <div className="settingsSectionHead"><div><span className="eyebrow">OUTLET BRANDING</span><h2>Design the customer experience</h2><p>Set your visual identity once. These choices control the outlet customer landing page on mobile and desktop.</p></div><button className="primary" onClick={saveBranding} disabled={saving}>Save branding</button></div>
    <form className="settingsPlanForm brandingConfigForm" onSubmit={saveBranding}>
      <div className="brandingFieldGroup"><div className="brandingFieldLabel"><b>Brand identity</b><span>Name, message and supporting copy.</span></div><div className="brandingFieldGrid">
        <label className="field"><span>Brand name</span><input value={branding.brandName} onChange={e=>setBranding({...branding,brandName:e.target.value})} maxLength="200" required/></label>
        <label className="field"><span>Tagline</span><input value={branding.tagline} onChange={e=>setBranding({...branding,tagline:e.target.value})} maxLength="300" placeholder="Fresh meals, made for your routine"/></label>
        <label className="field span2"><span>About</span><textarea rows="3" value={branding.about} onChange={e=>setBranding({...branding,about:e.target.value})} maxLength="4000" placeholder="Tell customers what makes your outlet special."/></label>
        <label className="field span2"><span>Highlights</span><input value={branding.healthHighlights} onChange={e=>setBranding({...branding,healthHighlights:e.target.value})} maxLength="2000" placeholder="Fresh ingredients, High protein, Chef prepared"/></label>
        <label className="field span2"><span>Footer text</span><input value={branding.footerText} onChange={e=>setBranding({...branding,footerText:e.target.value})} maxLength="1000" placeholder="Fresh meals. Better routines."/></label>
      </div></div>
      <div className="brandingFieldGroup"><div className="brandingFieldLabel"><b>Colours</b><span>Keep primary for actions and accents; secondary supports surfaces and highlights.</span></div><div className="brandingFieldGrid">
        <label className="colorField"><span>Primary colour</span><div><input type="color" value={branding.primaryColor} onChange={e=>setBranding({...branding,primaryColor:e.target.value})}/><code>{branding.primaryColor}</code></div></label>
        <label className="colorField"><span>Secondary colour</span><div><input type="color" value={branding.secondaryColor} onChange={e=>setBranding({...branding,secondaryColor:e.target.value})}/><code>{branding.secondaryColor}</code></div></label>
      </div></div>
      <div className="brandingFieldGroup"><div className="brandingFieldLabel"><b>Typography & component style</b><span>These settings create a consistent branded design system instead of styling each page separately.</span></div><div className="brandingFieldGrid">
        <label className="field"><span>Font</span><select value={branding.fontFamily} onChange={e=>setBranding({...branding,fontFamily:e.target.value})}><option>Inter</option><option>Poppins</option><option>DM Sans</option><option>Nunito</option><option>Manrope</option></select></label>
        <label className="field"><span>Visual theme</span><select value={branding.themeStyle} onChange={e=>setBranding({...branding,themeStyle:e.target.value})}><option>Fresh</option><option>Modern</option><option>Premium</option><option>Minimal</option></select></label>
        <label className="field"><span>Button shape</span><select value={branding.buttonStyle} onChange={e=>setBranding({...branding,buttonStyle:e.target.value})}><option>Rounded</option><option>Pill</option><option>Square</option></select></label>
        <label className="field"><span>Card style</span><select value={branding.cardStyle} onChange={e=>setBranding({...branding,cardStyle:e.target.value})}><option>Soft</option><option>Elevated</option><option>Flat</option></select></label>
      </div></div>
      <div className={`brandingLivePreview theme-${String(branding.themeStyle).toLowerCase()} cards-${String(branding.cardStyle).toLowerCase()}`} style={{'--brand-primary':branding.primaryColor,'--brand-secondary':branding.secondaryColor,'--brand-font':branding.fontFamily}}>
        <div className="brandingLivePreviewTop"><span className="brandingPreviewLogo">{branding.brandName?.slice(0,1).toUpperCase()||'F'}</span><div><b>{branding.brandName||'Your outlet'}</b><small>{branding.tagline||'Fresh meals, made for your routine'}</small></div></div>
        <div className="brandingPreviewHero"><div><span>LIVE CUSTOMER STYLE</span><h3>{branding.tagline||'Healthy meals made for your routine.'}</h3><p>{branding.about||'Preview your colours, typography, buttons and cards before customers see them.'}</p><button className={`brandingPreviewButton shape-${String(branding.buttonStyle).toLowerCase()}`}>Build my meal plan →</button></div><div className="brandingPreviewImage">{branding.heroImageUrl?<img src={branding.heroImageUrl} alt=""/>:<span>Hero image</span>}</div></div>
        <div className="brandingPreviewCards"><div>Morning menu</div><div>Afternoon menu</div><div>Fresh delivery</div></div>
      </div>
    </form>
    <div className="settingsDataList">
      <div className="settingsDataRow"><div><b>Logo</b><span>Used in the customer header, preview and outlet branding.</span></div><div className="settingsRowActions">{branding.logoUrl&&<img src={branding.logoUrl} alt="" style={{width:42,height:42,objectFit:'contain',borderRadius:9,border:'1px solid #dfe8e1'}}/>}<label className="secondary">Upload<input type="file" accept=".jpg,.jpeg,.png,.webp" style={{display:'none'}} onChange={e=>uploadBranding('logo',e.target.files?.[0])}/></label></div></div>
      <div className="settingsDataRow"><div><b>Hero image</b><span>Used on the customer landing page.</span></div><div className="settingsRowActions">{branding.heroImageUrl&&<img src={branding.heroImageUrl} alt="" style={{width:72,height:42,objectFit:'cover',borderRadius:9,border:'1px solid #dfe8e1'}}/>}<label className="secondary">Upload<input type="file" accept=".jpg,.jpeg,.png,.webp" style={{display:'none'}} onChange={e=>uploadBranding('hero',e.target.files?.[0])}/></label></div></div>
      <div className="settingsDataRow"><div><b>Favicon</b><span>Browser tab icon for the customer portal.</span></div><div className="settingsRowActions">{branding.faviconUrl&&<img src={branding.faviconUrl} alt="" style={{width:32,height:32,objectFit:'contain',borderRadius:7,border:'1px solid #dfe8e1'}}/>}<label className="secondary">Upload<input type="file" accept=".png,.ico,.jpg,.jpeg,.webp" style={{display:'none'}} onChange={e=>uploadBranding('favicon',e.target.files?.[0])}/></label></div></div>
      {brandingUploading&&<div className="settingsToolbar">Uploading {brandingUploading}…</div>}
    </div>
   </section>}
   {section==='domains'&&<section className="settingsSection">
    <div className="settingsSectionHead">
      <div><span className="eyebrow">CUSTOMER PORTAL DOMAINS</span><h2>Connect your customer website</h2><p>Every outlet gets a HealthApp platform address automatically. You can also request your own domain such as <b>www.fitfood.com</b>.</p></div>
    </div>
    <div className="settingsDataList">
      {domains.map(d=><div className="settingsDataRow" key={d.id||d.hostname}>
        <div>
          <b>{d.hostname}</b>
          <span>{d.type} domain · {d.status}{d.isPrimary?' · Primary':''}</span>
          {d.type==='Custom'&&<><small>Cloudflare: {d.providerStatus||'not checked'} · Validation: {d.providerValidationStatus||'not checked'}{d.providerError?' · '+d.providerError:''}</small>{d.status!=='Active'&&d.verificationName&&d.verificationValue&&<small>DNS {d.verificationRecordType||'TXT'}: <code>{d.verificationName}</code> = <code>{d.verificationValue}</code></small>}</>}
        </div>
        <div className="settingsRowActions">
          {d.type==='Custom'&&<><span className="pill">{d.status}</span>{d.status!=='Active'&&<button type="button" className="secondary" onClick={()=>verifyDomain(d.id)} disabled={saving}>Check DNS</button>}</>}
          {d.type==='Platform'&&<span className="pill">Automatic</span>}
        </div>
      </div>)}
      {!domains.length&&<div className="settingsEmpty">No customer portal domains are configured yet.</div>}
    </div>
    <form className="settingsInlineForm" onSubmit={requestDomain}>
      <label className="field span2"><span>Custom domain</span><input value={domainForm.hostname} onChange={e=>setDomainForm({...domainForm,hostname:e.target.value})} placeholder="www.fitfood.com" maxLength="253" required/></label>
      <label className="check"><input type="checkbox" checked={domainForm.isPrimary} onChange={e=>setDomainForm({...domainForm,isPrimary:e.target.checked})}/> Mark as primary</label>
      <button className="primary" disabled={saving||!domainForm.hostname.trim()}>Request domain</button>
    </form>
    <div className="settingsToolbar"><b>Verification</b><span>Cloudflare Pages checks the domain attachment and DNS validation. After adding the TXT record at your domain provider, use <b>Check DNS</b>. Super Admin activation is still required before the hostname becomes an active HealthApp tenant.</span></div>
   </section>}

   {section==='delivery'&&<section className="settingsSection"><div className="settingsSectionHead"><div><span className="eyebrow">DELIVERY SCHEDULE</span><h2>Choose your delivery days</h2><p>These days drive the weekly menu launch check and customer delivery calendar.</p></div><button className="primary" onClick={saveDays} disabled={saving}>Save days</button></div><div className="dayPicker">{DAYS.map(day=><button type="button" key={day} className={deliveryDays.includes(day)?'dayOption selected':'dayOption'} onClick={()=>setDeliveryDays(x=>x.includes(day)?x.filter(v=>v!==day):[...x,day])}><span>{day.slice(0,3)}</span><b>{day}</b></button>)}</div></section>}

   {section==='areas'&&<section className="settingsSection"><div className="settingsSectionHead"><div><span className="eyebrow">SERVICE AREAS</span><h2>Where will you deliver?</h2><p>Choose a simple delivery radius or select approved areas for tighter coverage.</p></div><button className="primary" onClick={saveDays} disabled={saving}>Save coverage</button></div><div className="coverageModeCards"><button type="button" className={coverageMode==='Radius'?'coverageModeCard selected':'coverageModeCard'} onClick={()=>setCoverageMode('Radius')}><b>📍 Delivery radius</b><span>Best for simple city coverage. Customers inside the circle are serviceable.</span></button><button type="button" className={coverageMode==='Areas'?'coverageModeCard selected':'coverageModeCard'} onClick={()=>setCoverageMode('Areas')}><b>◎ Selected areas</b><span>Choose only the approved city areas configured by HealthApp.</span></button></div>{coverageMode==='Radius'?<><div className="coverageRadiusControls"><label className="field"><span>Radius (km)</span><input type="number" min="1" max="100" step=".5" value={serviceRadiusKm} onChange={e=>setServiceRadiusKm(e.target.value)}/><small>Drag the radius on the map conceptually by changing this value. The outlet pin is the centre.</small></label><div className="radiusQuickChoices">{[5,10,15,20,30].map(k=><button type="button" className={Number(serviceRadiusKm)===k?'active':''} key={k} onClick={()=>setServiceRadiusKm(k)}>{k} km</button>)}</div></div><div className="coverageMapWrap">{data?.latitude||data?.longitude?<MapContainer center={[data.latitude,data.longitude]} zoom={11} scrollWheelZoom className="coverageMap"><TileLayer attribution="&copy; OpenStreetMap contributors" url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png"/><CircleMarker center={[data.latitude,data.longitude]} radius={9}/><Circle center={[data.latitude,data.longitude]} radius={Number(serviceRadiusKm||0)*1000} pathOptions={{fillOpacity:.12,weight:2}}/></MapContainer>:<div className="settingsEmpty">Outlet map coordinates are not available.</div>}</div></>:<><div className="settingsToolbar"><b>{selectedAreas.length}</b> approved areas selected</div><div className="settingsAreaGrid">{areas.map(a=><label className={selectedAreas.includes(a.id)?'settingsArea checked':'settingsArea'} key={a.id}><input type="checkbox" checked={selectedAreas.includes(a.id)} onChange={e=>setSelectedAreas(e.target.checked?[...selectedAreas,a.id]:selectedAreas.filter(x=>x!==a.id))}/><div><b>{a.name}</b><span>{a.city} · {a.pincode}</span></div></label>)}</div></>}</section>}

   {section==='pricing'&&<section className="settingsSection"><div className="settingsSectionHead"><div><span className="eyebrow">DELIVERY PRICING</span><h2>Configure distance-based fees</h2><p>Customers are charged according to the nearest matching distance slab.</p></div></div><form className="settingsInlineForm" onSubmit={addPricing}><label className="field"><span>Up to km</span><input type="number" min="0.1" step=".1" value={priceForm.maxDistanceKm} onChange={e=>setPriceForm({...priceForm,maxDistanceKm:e.target.value})} required/></label><label className="field"><span>Fee (₹)</span><input type="number" min="0" step=".01" value={priceForm.fee} onChange={e=>setPriceForm({...priceForm,fee:e.target.value})} required/></label><button className="primary" disabled={saving}>Add slab</button></form><div className="settingsDataList">{pricing.map(p=><div className="settingsDataRow" key={p.id}><div><b>≤ {p.maxDistanceKm} km</b><span>Delivery fee</span></div><strong>{money(p.fee)}</strong></div>)}{!pricing.length&&<div className="settingsEmpty">Add at least one delivery pricing slab.</div>}</div></section>}

   {section==='discounts'&&<section className="settingsSection"><div className="settingsSectionHead"><div><span className="eyebrow">SUBSCRIPTION DISCOUNTS</span><h2>Configure customer subscription savings</h2><p>Use quantity and duration based discounts to reward committed customers.</p></div></div><form className="settingsDiscountForm" onSubmit={saveTier}><label className="field"><span>Min meals</span><input type="number" min="1" value={tierForm.minMeals} onChange={e=>setTierForm({...tierForm,minMeals:e.target.value})}/></label><label className="field"><span>Max meals</span><input type="number" min="1" value={tierForm.maxMeals} onChange={e=>setTierForm({...tierForm,maxMeals:e.target.value})}/></label><label className="field"><span>1 week %</span><input type="number" min="0" max="100" step=".1" value={tierForm.oneWeekPercent} onChange={e=>setTierForm({...tierForm,oneWeekPercent:e.target.value})}/></label><label className="field"><span>2 weeks %</span><input type="number" min="0" max="100" step=".1" value={tierForm.twoWeeksPercent} onChange={e=>setTierForm({...tierForm,twoWeeksPercent:e.target.value})}/></label><label className="field"><span>1 month %</span><input type="number" min="0" max="100" step=".1" value={tierForm.oneMonthPercent} onChange={e=>setTierForm({...tierForm,oneMonthPercent:e.target.value})}/></label><button className="primary" disabled={saving}>{editTier?'Update tier':'Add tier'}</button></form><div className="settingsDataList">{tiers.map(t=><div className="settingsDataRow" key={t.id}><div><b>{t.minMeals} – {t.maxMeals===null?'∞':t.maxMeals} meals</b><span>1W {t.oneWeekPercent}% · 2W {t.twoWeeksPercent}% · 1M {t.oneMonthPercent}%</span></div><div className="settingsRowActions"><button className="secondary" onClick={()=>{setEditTier(t);setTierForm({...t,maxMeals:t.maxMeals===null?'':t.maxMeals})}}>Edit</button><button className="dangerText" onClick={()=>removeTier(t)}>Delete</button></div></div>)}</div></section>}

   {section==='meal-plans'&&<section className="settingsSection">
    <div className="settingsSectionHead"><div><span className="eyebrow">CUSTOMER PACKAGE CONFIGURATION</span><h2>Recommended packages & custom pricing</h2><p>Control what customers see when building a package. Preplanned packages always use the fixed outlet price; custom packages can be calculated instantly or reviewed by the outlet before payment.</p></div></div>
    <form className="packageSettingsCard" onSubmit={savePackageSettings}>
      <div className="packagePricingModes">
        <button type="button" className={packageSettings.customPackagePricingMode==='Calculated'?'packagePricingMode selected':'packagePricingMode'} onClick={()=>setPackageSettings(x=>({...x,customPackagePricingMode:'Calculated'}))}><b>Instant calculated price</b><span>Customer sees the calculated package total immediately.</span></button>
        <button type="button" className={packageSettings.customPackagePricingMode==='ReviewRequired'?'packagePricingMode selected':'packagePricingMode'} onClick={()=>setPackageSettings(x=>({...x,customPackagePricingMode:'ReviewRequired'}))}><b>Outlet review required</b><span>Customer submits the package; payment appears only after your team confirms the final package price.</span></button>
      </div>
      <div className="packageDisplayOptions">
       <label><input type="checkbox" checked={packageSettings.showPackagePriceToCustomer} onChange={e=>setPackageSettings(x=>({...x,showPackagePriceToCustomer:e.target.checked}))}/><span><b>Show package price</b><small>Display the calculated/fixed package total to customers.</small></span></label>
       <label><input type="checkbox" checked={packageSettings.showMealPriceToCustomer} onChange={e=>setPackageSettings(x=>({...x,showMealPriceToCustomer:e.target.checked}))}/><span><b>Show meal price</b><small>Display individual meal prices in the public menu, meal picker and customer meal details. The backend always uses the configured meal price for package calculation.</small></span></label>
       <label><input type="checkbox" checked={packageSettings.showDeliveryFeeToCustomer} onChange={e=>setPackageSettings(x=>({...x,showDeliveryFeeToCustomer:e.target.checked}))}/><span><b>Show delivery charge</b><small>Display the delivery charge separately before payment.</small></span></label>
      </div>
      <div className="modalActions"><button className="primary" disabled={saving}>Save customer package settings</button></div>
    </form>
    <div className="settingsSectionHead"><div><span className="eyebrow">PREPLANNED PACKAGES</span><h2>Create outlet recommendations</h2><p>These are shown to customers first for their delivery city. The price below is the fixed package price.</p></div></div>
    <form className="settingsPlanForm" onSubmit={createMealPlan}>
      <label className="field span2"><span>Package name</span><input value={mealPlanForm.name} onChange={e=>setMealPlanForm({...mealPlanForm,name:e.target.value})} placeholder="High Protein 7-Day Plan" required/></label>
      <label className="field"><span>Frequency</span><select value={mealPlanForm.frequency} onChange={e=>setMealPlanForm({...mealPlanForm,frequency:e.target.value})}><option>Weekly</option><option>Biweekly</option><option>Monthly</option></select></label>
      <label className="field"><span>Duration (days)</span><input type="number" min="1" max="31" value={mealPlanForm.durationDays} onChange={e=>setMealPlanForm({...mealPlanForm,durationDays:e.target.value})}/></label>
      <label className="field"><span>Meals / day</span><input type="number" min="1" max="8" value={mealPlanForm.mealsPerDay} onChange={e=>setMealPlanForm({...mealPlanForm,mealsPerDay:e.target.value})}/></label>
      <label className="field"><span>Fixed package price (₹)</span><input type="number" min="0" step=".01" value={mealPlanForm.price} onChange={e=>setMealPlanForm({...mealPlanForm,price:e.target.value})}/></label>
      <label className="field"><span>Delivery city</span><input value={mealPlanForm.availableCity||data?.city||''} onChange={e=>setMealPlanForm({...mealPlanForm,availableCity:e.target.value})} placeholder={data?.outletCity||'Outlet city'}/></label>
      <label className="field span2 packagePreplannedCheck"><input type="checkbox" checked={Boolean(mealPlanForm.isPreplanned)} onChange={e=>setMealPlanForm({...mealPlanForm,isPreplanned:e.target.checked,availableCity:e.target.checked?(mealPlanForm.availableCity||data?.city||''):''})}/><span><b>Show as recommended preplanned package</b><small>Customers can select this package from the recommendation dropdown for the selected city.</small></span></label>
      <label className="field span2"><span>Description</span><textarea rows="2" value={mealPlanForm.description} onChange={e=>setMealPlanForm({...mealPlanForm,description:e.target.value})}/></label>
      <button className="primary" disabled={saving}>Create package</button>
    </form>
    <div className="settingsDataList">{mealPlans.map(p=><div className="settingsDataRow" key={p.id}><div><b>{p.name} {p.isPreplanned&&<span className="pill green">Recommended</span>}</b><span>{p.frequency} · {p.durationDays||7} days · {p.mealsPerDay} meals/day{p.isPreplanned&&p.availableCity?' · '+p.availableCity:''}</span></div><strong>{money(p.price)}</strong></div>)}{!mealPlans.length&&<div className="settingsEmpty">Create your first customer package.</div>}</div>
   </section>}

   {section==='tax'&&<section className="settingsSection"><div className="settingsSectionHead"><div><span className="eyebrow">TAX & GST</span><h2>Customer tax treatment</h2><p>Used in customer package quotes and financial reporting.</p></div><button className="primary" onClick={saveTax} disabled={saving}>Save tax settings</button></div><div className="settingsTaxGrid"><label className="field"><span>Restaurant GST %</span><input type="number" min="0" max="100" step=".01" value={tax.restaurantGstRate} onChange={e=>setTax({...tax,restaurantGstRate:e.target.value})}/></label><div className="taxModeCards"><button type="button" className={tax.restaurantGstMode==='Exclusive'?'taxModeCard selected':'taxModeCard'} onClick={()=>setTax({...tax,restaurantGstMode:'Exclusive'})}><b>GST Exclusive</b><span>GST is added at checkout.</span></button><button type="button" className={tax.restaurantGstMode==='Inclusive'?'taxModeCard selected':'taxModeCard'} onClick={()=>setTax({...tax,restaurantGstMode:'Inclusive'})}><b>GST Inclusive</b><span>GST is extracted from the displayed price.</span></button></div></div></section>}

   {section==='legal'&&<section className="settingsSection">
    <div className="settingsSectionHead"><div><span className="eyebrow">CUSTOMER LEGAL & POLICIES</span><h2>Control what your customers agree to</h2><p>These documents belong to your outlet. Save drafts while editing and publish only when the mandatory customer documents and your commercial rules are ready.</p></div><div className="legalPublishStatus"><span className={legal.publishedVersionId?'pill green':'pill'}>{legal.publishedVersionId?'Published':'Draft'}</span>{legal.publishedVersion&&<small>Live v{legal.publishedVersion}{legal.publishedEffectiveDateUtc?' · Effective '+new Date(legal.publishedEffectiveDateUtc).toLocaleDateString():''}</small>}{legal.legalVersion&&legal.legalVersion!==legal.publishedVersion&&<small>Draft v{legal.legalVersion}</small>}</div></div>
    <form className="legalEditorForm" onSubmit={e=>saveLegal(e,false)}>
      <div className="legalEditorIntro"><b>Outlet-owned customer documents</b><span>These policies appear to customers under <b>{data?.outletName||'your outlet'}</b>. Keep them clear and consistent with applicable law. Saving a draft does not publish it.</span></div>
      <label className="field"><span>Customer Terms & Conditions *</span><textarea rows="12" value={legal.customerTermsAndConditions} onChange={e=>setLegal({...legal,customerTermsAndConditions:e.target.value})} placeholder="Subscription terms, prices, cancellation, refunds, customer responsibilities, complaints and applicable-law provisions." required/></label>
      <label className="field"><span>Customer Privacy Policy *</span><textarea rows="12" value={legal.customerPrivacyPolicy} onChange={e=>setLegal({...legal,customerPrivacyPolicy:e.target.value})} placeholder="Data collected, purposes, health/allergy information, sharing, retention, rights, contact details and complaint routes." required/></label>
      <div className="legalTwoCol">
       <label className="field"><span>Cancellation & Refund Policy *</span><textarea rows="7" value={legal.cancellationRefundPolicy} onChange={e=>setLegal({...legal,cancellationRefundPolicy:e.target.value})} placeholder="Cancellation cutoff, refund eligibility, credits, service failures and refund timing."/></label>
       <label className="field"><span>Meal Skip & Rescheduling Policy *</span><textarea rows="7" value={legal.mealSkipReschedulePolicy} onChange={e=>setLegal({...legal,mealSkipReschedulePolicy:e.target.value})} placeholder="Free skip cutoff, late skip charge, rescheduling window, expiry and exceptions."/></label>
       <label className="field"><span>Delivery Policy *</span><textarea rows="7" value={legal.deliveryPolicy} onChange={e=>setLegal({...legal,deliveryPolicy:e.target.value})} placeholder="Coverage, delivery windows, exact map location, failed delivery and address-change rules."/></label>
       <label className="field"><span>Allergen & Dietary Disclaimer *</span><textarea rows="7" value={legal.allergenDietaryDisclaimer} onChange={e=>setLegal({...legal,allergenDietaryDisclaimer:e.target.value})} placeholder="Ingredients, allergens, cross-contact risk and customer responsibility."/></label>
       <label className="field span2"><span>Payment, Pricing & Promotional Terms *</span><textarea rows="7" value={legal.paymentPricingPromotionalTerms} onChange={e=>setLegal({...legal,paymentPricingPromotionalTerms:e.target.value})} placeholder="GST/taxes, discount codes, payment failures, promotional eligibility and pricing rules."/></label>
      </div>
      <div className="legalControlGrid">
       <label className="field"><span>Document version</span><input value={legal.legalVersion} onChange={e=>setLegal({...legal,legalVersion:e.target.value})} maxLength="40" placeholder="1.0" required/></label>
       <label className="field"><span>Effective date</span><input type="date" value={legal.legalEffectiveDateUtc} onChange={e=>setLegal({...legal,legalEffectiveDateUtc:e.target.value})}/></label>
       <div className="legalPublishGuidance"><span className="pill green">{legal.legalPoliciesPublished?'Published '+(legal.publishedVersion||'version'):'Not published'}</span><span>Saving a draft never changes the live customer document. To publish a change, increase the document version and use <b>Publish version</b>.</span></div>
      </div>
      <div className="modalActions"><button type="submit" className="secondary" disabled={saving}>Save draft</button><button type="button" className="primary" disabled={saving} onClick={()=>saveLegal(null,true)}>Publish version →</button></div>
    </form>
    <div className="legalVersionHistory"><div className="legalHistoryHead"><div><span className="eyebrow">VERSION HISTORY</span><h3>Published customer-policy versions</h3><p>Published versions are immutable and retained for customer acceptance records.</p></div><span className="pill">{legal.versionHistory.length} version{legal.versionHistory.length===1?'':'s'}</span></div>{legal.versionHistory.length?<div className="legalHistoryList">{legal.versionHistory.map(v=><div className={v.isPublished?'legalHistoryRow current':'legalHistoryRow'} key={v.id}><div><b>Version {v.version}</b>{v.isPublished&&<span className="pill green">Current</span>}<small>Effective {new Date(v.effectiveDateUtc).toLocaleDateString()} · Created {new Date(v.createdAtUtc).toLocaleDateString()}</small></div><code title={v.contentHash}>SHA-256 {String(v.contentHash||'').slice(0,12)}…</code></div>)}</div>:<div className="settingsEmpty">No published versions yet.</div>}</div>
    <div className="legalQuickLinks"><a href="?legal=saas-terms">HealthApp SaaS Terms</a><a href="?legal=dpa">HealthApp DPA</a><a href={getCustomerLegalUrl('terms')} target="_blank" rel="noreferrer">Preview customer terms ↗</a><a href={getCustomerLegalUrl('privacy')} target="_blank" rel="noreferrer">Preview customer privacy ↗</a></div>
   </section>}

   {section==='billing'&&<section className="settingsSection"><div className="settingsSectionHead"><div><span className="eyebrow">HEALTHAPP BILLING</span><h2>Plan & billing</h2><p>Change the outlet's SaaS plan here. Billing remains part of settings rather than the operating navigation.</p></div></div>{billing&&<div className="currentBilling"><span>CURRENT PLAN</span><b>{billing.planName}</b><strong>{money(billing.subscriptionFee)} <small>/ {billing.billingCycle}</small></strong><p>{billing.activeCustomers} active customers · {billing.transactionFeePercent}% transaction fee</p></div>}<form className="billingSettingsForm" onSubmit={changePlan}><label className="field"><span>HealthApp plan</span><select value={planChoice} onChange={e=>setPlanChoice(e.target.value)}><option value="">Select a plan</option>{saasPlans.map(p=><option value={p.id} key={p.id}>{p.name} · {money(cycle==='Annual'?p.annualFee:p.monthlyFee)} / {cycle.toLowerCase()}</option>)}</select></label><div className="cycleToggle"><button type="button" className={cycle==='Monthly'?'active':''} onClick={()=>setCycle('Monthly')}>Monthly</button><button type="button" className={cycle==='Annual'?'active':''} onClick={()=>setCycle('Annual')}>Annual</button></div><button className="primary" disabled={!planChoice||saving}>Save billing plan</button></form></section>}
  </div></div>
  {previewOpen&&<div className="settingsPreviewBackdrop" onMouseDown={e=>e.target===e.currentTarget&&setPreviewOpen(false)}><div className="settingsPreviewModal"><div className="settingsPreviewHeader"><div><span className="eyebrow">CUSTOMER EXPERIENCE PREVIEW</span><h2>{data?.outletName||'Outlet'}</h2><p>Live preview of the customer landing page using this outlet's current branding and menu configuration.</p></div><button className="settingsPreviewClose" onClick={()=>setPreviewOpen(false)}>×</button></div><div className="settingsPreviewToolbar"><span>Preview mode · Changes appear after the customer page reloads.</span>{getCustomerPreviewUrl()&&<a className="secondary smallBtn" href={getCustomerPreviewUrl()} target="_blank" rel="noreferrer">Open in new tab ↗</a>}</div><div className="settingsPreviewFrameWrap">{getCustomerPreviewUrl()?<iframe title="Customer experience preview" src={getCustomerPreviewUrl()} className="settingsPreviewFrame"/>:<div className="settingsPreviewEmpty">Customer portal preview URL is not configured yet.</div>}</div></div></div>}
  {confirmLive&&<div className="settingsConfirmBackdrop"><div className="settingsConfirm"><span className="settingsConfirmIcon">✓</span><h3>Make this outlet live?</h3><p>This will publish the outlet to the customer marketplace. You can do this only after the required launch checks are complete.</p><div><button className="secondary" onClick={()=>setConfirmLive(false)}>Not yet</button><button className="primary" onClick={goLive}>Yes, make it live</button></div></div></div>}
 </div>;
}
