import React,{useEffect,useState}from'react';
import{createRoot}from'react-dom/client';
import{auth,admin,currentUser,money,API_URL}from'@healthapp/shared';
import'./styles.css';

function App(){
 const[u,setU]=useState(currentUser());
 const[login,setLogin]=useState({email:'admin@healthapp.test',password:'demo'});
 const[data,setData]=useState({});
 const[cities,setCities]=useState([]);
 const[form,setForm]=useState({city:'Hyderabad',state:'Telangana',country:'India',latitude:17.385,longitude:78.4867,isEnabled:true});
 const[error,setError]=useState('');
 const[toast,setToast]=useState('');
 const[loading,setLoading]=useState(false);
 const[verification,setVerification]=useState([]),[selectedVerification,setSelectedVerification]=useState(null),[verificationNotes,setVerificationNotes]=useState('');
 const notify=m=>{setToast(m);setTimeout(()=>setToast(''),2200)};
 const fileUrl=u=>{if(!u)return'';return u.startsWith('http')?u:(API_URL?new URL(API_URL).origin+u:u)};
 const reload=async()=>{
   try{
     setLoading(true);
     const[d,o,us,r,cs,v]=await Promise.all([admin.dashboard(),admin.outlets(),admin.users(),admin.revenue(),admin.cities(),admin.outletOnboardingPending()]);
     setData({d,o,us,r});setCities(cs||[]);setVerification(v||[]);setError('');
   }catch(e){setError(e.message||'Unable to load admin data.')}finally{setLoading(false)}
 };
 useEffect(()=>{if(u)reload()},[u]);
 const sign=async e=>{e.preventDefault();try{const x=await auth.login(login);setU(x.user);notify('Welcome back')}catch(e){setError(e.message||'Sign in failed')}};
 const createCity=async()=>{try{setLoading(true);await admin.createCity(form);await reload();notify(form.city+' is now available for HealthApp') }catch(e){setError(e.message||'Unable to save city')}finally{setLoading(false)}};
 const toggle=async city=>{try{setLoading(true);await admin.setCityEnabled(city.id,!city.isEnabled);await reload();notify(city.city+' '+(!city.isEnabled?'enabled':'disabled'))}catch(e){setError(e.message||'Unable to update city')}finally{setLoading(false)}};
 if(!u)return <div className="auth"><form onSubmit={sign}><div className="brand">H<span>ealthe</span></div><h1>Super Admin</h1><p>Control where the HealthApp marketplace is live.</p><input value={login.email} onChange={e=>setLogin({...login,email:e.target.value})} placeholder="Email"/><input type="password" value={login.password} onChange={e=>setLogin({...login,password:e.target.value})} placeholder="Password"/><button disabled={loading}>Sign in</button><small>Demo: admin@healthapp.test / demo</small>{error&&<div className="error">{error}</div>}</form></div>;
 return <div className="app"><header><div><b>HealthApp</b><span>Super Admin</span></div><div className="headerRight"><span>{u.email}</span><button onClick={()=>{auth.logout();setU(null)}}>Logout</button></div></header>
 <main>
   <section className="hero"><div><span className="eyebrow">PLATFORM CONTROL</span><h1>Service cities</h1><p>Enable a city to launch HealthApp there. Customers can pin any location in an enabled city; outlets determine delivery serviceability.</p></div><div className="heroBadge">🌍 {cities.filter(x=>x.isEnabled).length} live cities</div></section>
   {error&&<div className="errorBanner">⚠ {error}<button onClick={()=>setError('')}>×</button></div>}
   <div className="stats"><div><span>Outlets</span><b>{data.d?.outlets??0}</b></div><div><span>Users</span><b>{data.d?.users??0}</b></div><div><span>Revenue</span><b>{money(data.r?.totalRevenue||0)}</b></div></div>
   <section className="panel verificationPanel"><div className="panelHead"><div><span className="eyebrow">OUTLET VERIFICATION</span><h2>Pending applications</h2><p>Review paid outlet onboarding applications and approve or reject account activation.</p></div><span className="verificationCount">{verification.length} pending</span></div>{verification.length?<div className="verificationList">{verification.map(x=><div className="verificationRow" key={x.id}><div><b>{x.outletName||'Unnamed outlet'}</b><span>{x.ownerName||'Owner not supplied'} · {x.city||'City not supplied'} · {x.businessType}</span></div><div><b>{x.planName} · {x.paymentStatus}</b><span>{x.submittedAtUtc?new Date(x.submittedAtUtc).toLocaleString():'Not submitted'}</span></div><button onClick={async()=>{try{setLoading(true);setSelectedVerification(await admin.outletOnboardingDetail(x.id));setVerificationNotes('')}catch(e){setError(e.message||'Unable to load application')}finally{setLoading(false)}}}>Review →</button></div>)}</div>:<div className="empty">No outlet applications are waiting for verification.</div>}</section>
   <section className="panel"><div className="panelHead"><div><span className="eyebrow">LIVE OPERATING AREAS</span><h2>Enabled cities</h2><p>City availability is the only platform-level geographic control.</p></div></div><div className="cityList">{cities.map(city=><div className={city.isEnabled?'cityRow enabled':'cityRow'} key={city.id}><div className="cityIcon">📍</div><div><b>{city.city}</b><span>{city.state} · {city.country}</span></div><div className="cityStatus">{city.isEnabled?'Live':'Disabled'}</div><button className={city.isEnabled?'toggle on':'toggle'} disabled={loading} onClick={()=>toggle(city)}>{city.isEnabled?'Disable':'Enable'}</button></div>)}</div>{!cities.length&&<div className="empty">No service cities configured.</div>}</section>
   <section className="panel"><div className="panelHead"><div><span className="eyebrow">LAUNCH A CITY</span><h2>Add or enable city</h2><p>Set the city centre used to initially position the customer map. Delivery is handled by outlets.</p></div></div><div className="formGrid"><label>City<input value={form.city} onChange={e=>setForm({...form,city:e.target.value})}/></label><label>State<input value={form.state} onChange={e=>setForm({...form,state:e.target.value})}/></label><label>Country<input value={form.country} onChange={e=>setForm({...form,country:e.target.value})}/></label><label>Latitude<input type="number" step="0.000001" value={form.latitude} onChange={e=>setForm({...form,latitude:Number(e.target.value)})}/></label><label>Longitude<input type="number" step="0.000001" value={form.longitude} onChange={e=>setForm({...form,longitude:Number(e.target.value)})}/></label><label className="check"><input type="checkbox" checked={form.isEnabled} onChange={e=>setForm({...form,isEnabled:e.target.checked})}/> Enable immediately</label></div><div className="actions"><button onClick={createCity} disabled={loading}>Save city</button></div></section>
   <section className="panel"><div className="panelHead"><div><span className="eyebrow">OUTLETS</span><h2>Current outlets</h2><p>Outlet delivery radius and pricing are configured by each outlet.</p></div></div><div className="outletList">{(data.o||[]).map(x=><div className="outletRow" key={x.id}><div><b>{x.name}</b><span>{x.city}, {x.state}</span></div><span className="pill">{x.status}</span></div>)}</div></section>
 </main>{selectedVerification&&<div className="verifyBackdrop"><div className="verifyModal"><div className="verifyModalHead"><div><span className="eyebrow">OUTLET APPLICATION</span><h2>{selectedVerification.outletName||'Unnamed outlet'}</h2><p>{selectedVerification.planName} · {selectedVerification.billingCycle} · {selectedVerification.paymentStatus}</p></div><button onClick={()=>setSelectedVerification(null)}>×</button></div><div className="verifyGrid"><section><h3>Business</h3><div className="verifyFacts"><span>Type</span><b>{selectedVerification.businessType}</b><span>City</span><b>{selectedVerification.city}, {selectedVerification.state} {selectedVerification.pincode}</b><span>Address</span><b>{[selectedVerification.addressLine1,selectedVerification.addressLine2].filter(Boolean).join(', ')}</b><span>Description</span><b>{selectedVerification.description||'—'}</b></div></section><section><h3>Owner & identity</h3><div className="verifyFacts"><span>Owner</span><b>{selectedVerification.ownerName}</b><span>Email</span><b>{selectedVerification.ownerEmail}</b><span>Phone</span><b>{selectedVerification.ownerPhone}</b><span>Aadhaar</span><b>XXXX XXXX {String(selectedVerification.aadhaarNumber||'').slice(-4)}</b><span>Business PAN</span><b>{selectedVerification.businessPan||'—'}</b><span>GST</span><b>{selectedVerification.gstNumber||'—'}</b></div></section><section className="verifyDocs"><h3>Documents</h3><div className="verifyDocList">{[['Aadhaar card',selectedVerification.aadhaarCardUrl],['Business registration',selectedVerification.businessRegistrationUrl],['Business PAN',selectedVerification.businessPanDocumentUrl],['GST certificate',selectedVerification.gstCertificateUrl]].filter(([,url])=>url).map(([label,url])=><a key={label} href={fileUrl(url)} target="_blank" rel="noreferrer"><span>✓</span>{label}<small>Open document ↗</small></a>)}</div></section><section><h3>Verification decision</h3><textarea value={verificationNotes} onChange={e=>setVerificationNotes(e.target.value)} placeholder="Add verification notes (required when rejecting)."/><div className="verifyActions"><button className="rejectBtn" disabled={loading||!verificationNotes.trim()} onClick={async()=>{try{setLoading(true);await admin.decideOutletOnboarding(selectedVerification.id,{approve:false,notes:verificationNotes});setSelectedVerification(null);await reload();notify('Application rejected')}catch(e){setError(e.message||'Unable to reject application')}finally{setLoading(false)}}}>Reject</button><button className="approveBtn" disabled={loading} onClick={async()=>{try{setLoading(true);await admin.decideOutletOnboarding(selectedVerification.id,{approve:true,notes:verificationNotes});setSelectedVerification(null);await reload();notify('Outlet approved and activated')}catch(e){setError(e.message||'Unable to approve application')}finally{setLoading(false)}}}>Approve & activate</button></div></section></div></div></div>}{toast&&<div className="toast">✓ {toast}</div>}</div>
}
createRoot(document.getElementById('root')).render(<App/>);
