import React,{useEffect,useMemo,useState}from'react';
import{admin,money}from'@healthapp/shared';

const formatDate=v=>v?new Date(v).toLocaleDateString('en-IN',{day:'2-digit',month:'short',year:'numeric'}):'—';
const role=s=>String(s||'').replace('OutletAdmin','Outlet Admin').replace('OutletManager','Manager').replace('KitchenStaff','Kitchen Staff');
const tone=s=>{
 const v=String(s||'').toLowerCase();
 if(v.includes('live')||v.includes('active')||v.includes('paid')||v.includes('delivered'))return'success';
 if(v.includes('pending')||v.includes('preparing')||v.includes('scheduled'))return'warning';
 if(v.includes('cancel')||v.includes('fail')||v.includes('disable'))return'danger';
 return'neutral';
};
const Pill=({status})=><span className={'statusPill '+tone(status)}>{status||'Unknown'}</span>;
const Empty=({children})=><div className="emptyState">{children}</div>;
const Field=({label,value})=><><span>{label}</span><b>{value||'—'}</b></>;

export default function Outlet360({outletId,onBack}){
 const[data,setData]=useState(null);
 const[tab,setTab]=useState('overview');
 const[loading,setLoading]=useState(true);
 const[error,setError]=useState('');
 const[reactivation,setReactivation]=useState(null);
 const[reactivationPlan,setReactivationPlan]=useState('');
 const[reactivationCycle,setReactivationCycle]=useState('Monthly');
 const[reactivationReason,setReactivationReason]=useState('Super Admin reactivation');
 const[reactivating,setReactivating]=useState(false);
 useEffect(()=>{let active=true;(async()=>{try{setLoading(true);setError('');const[x,options]=await Promise.all([admin.outlet360(outletId),admin.reactivationOptions(outletId)]);if(active){setData(x);setReactivation(options);if(options?.currentSaaSPlanId)setReactivationPlan(options.currentSaaSPlanId);else if(options?.availablePlans?.length)setReactivationPlan(options.availablePlans[0].id)}}}catch(e){if(active)setError(e.message||'Unable to load Outlet 360')}finally{if(active)setLoading(false)}})();return()=>{active=false}},[outletId]);
 const tabs=useMemo(()=>[
  ['overview','Overview'],['business','Business'],['users','Users'],['customers','Customers'],['subscriptions','Subscriptions'],['operations','Operations'],['kitchen','Kitchen'],['finance','Finance'],['domain','Domain'],['legal','Legal']
 ],[]);
 if(loading)return <section><div className="pageIntro"><div><span className="eyebrow">TENANT 360</span><h1>Loading workspace…</h1><p>Preparing the tenant snapshot.</p></div></div><div className="card loadingCard"><div className="skeletonLine"/><div className="skeletonLine short"/><div className="skeletonLine"/><div className="skeletonLine short"/></div></section>;
 if(error||!data)return <section><div className="pageIntro"><div><span className="eyebrow">TENANT 360</span><h1>Tenant unavailable</h1><p>{error||'The outlet could not be found.'}</p></div><button className="secondaryBtn" onClick={onBack}>Back to outlets</button></div></section>;
 const o=data.outlet||{},b=data.billing,t=data.taxSettings||{};
 return <section>
  <div className="pageIntro"><div><span className="eyebrow">TENANT 360</span><h1>{o.name||'Outlet'}</h1><p>Read-only support workspace for the tenant. Outlet-owned configuration is inspected here without silently impersonating the outlet.</p></div><button className="secondaryBtn" onClick={onBack}>← Back to outlets</button></div>
  <div className="tenantHero"><div className="avatarCircle tenantHeroAvatar">{String(o.name||'O').trim().charAt(0).toUpperCase()}</div><div className="tenantHeroText"><div className="tenantHeroTitle"><h2>{o.name||'Unnamed outlet'}</h2><Pill status={o.status}/></div><p>{o.slug||'—'} · {[o.city,o.state,o.pincode].filter(Boolean).join(', ')||'Location not supplied'}</p><small>{data.group?.name||'Unassigned group'} · {b?.planName||'No SaaS plan'} · {o.deliveryCoverageMode||'Radius'} coverage</small></div>{reactivation?.canReactivate&&<div className="reactivationCard"><div><span className="eyebrow">ACCOUNT RECOVERY</span><b>Reactivate this outlet</b><small>{reactivation.trialStatus==='Expired'?'The trial has expired.':'The SaaS subscription has expired.'} Existing customers, menus and outlet data are retained.</small></div><div className="reactivationForm"><select value={reactivationPlan} onChange={e=>setReactivationPlan(e.target.value)}>{(reactivation.availablePlans||[]).map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select><select value={reactivationCycle} onChange={e=>setReactivationCycle(e.target.value)}><option value="Monthly">Monthly</option><option value="Annual">Annual</option></select><input value={reactivationReason} onChange={e=>setReactivationReason(e.target.value)} placeholder="Reason" /><button className="primaryBtn compactBtn" disabled={reactivating||!reactivationPlan||!reactivationReason.trim()} onClick={async()=>{if(!window.confirm('Reactivate this outlet and make the selected SaaS subscription active?'))return;try{setReactivating(true);await admin.reactivateOutlet(outletId,{saasPlanId:reactivationPlan,billingCycle:reactivationCycle,reason:reactivationReason.trim()});const[x,options]=await Promise.all([admin.outlet360(outletId),admin.reactivationOptions(outletId)]);setData(x);setReactivation(options);setTab('overview')}catch(e){setError(e.message||'Unable to reactivate outlet')}finally{setReactivating(false)}}}>{reactivating?'Reactivating…':'Reactivate outlet'}</button></div></div>}</div>
  <div className="metricGrid tenantMetrics"><div className="metricCard"><div className="metricTop"><span>Customers</span></div><b>{data.customerUsers||0}</b><small>{data.activeCustomers||0} active</small></div><div className="metricCard"><div className="metricTop"><span>Subscriptions</span></div><b>{data.totalSubscriptions||0}</b><small>{data.activeSubscriptions||0} active</small></div><div className="metricCard"><div className="metricTop"><span>Deliveries today</span></div><b>{data.deliveriesToday||0}</b><small>{data.deliveries30Days||0} in 30 days</small></div><div className="metricCard"><div className="metricTop"><span>30d transaction volume</span></div><b>{money(data.revenue30Days||0)}</b><small>Tenant transaction records</small></div><div className="metricCard"><div className="metricTop"><span>Restaurant GST · 30d</span></div><b>{money(data.restaurantGst30Days||0)}</b><small>{t.restaurantGstRate||0}% · {t.restaurantGstMode||'Exclusive'}</small></div><div className="metricCard"><div className="metricTop"><span>Platform fee · 30d</span></div><b>{money(data.platformFee30Days||0)}</b><small>HealthApp service-fee records</small></div></div>
  <div className="tenantTabs">{tabs.map(([id,label])=><button type="button" key={id} className={tab===id?'active':''} onClick={()=>setTab(id)}>{label}</button>)}</div>
  {tab==='overview'&&<Overview data={data}/>}
  {tab==='business'&&<Business data={data}/>}
  {tab==='users'&&<Users data={data}/>}
  {tab==='customers'&&<Customers data={data}/>}
  {tab==='subscriptions'&&<Subscriptions data={data}/>}
  {tab==='operations'&&<Operations data={data}/>}
  {tab==='kitchen'&&<Kitchen data={data}/>}
  {tab==='finance'&&<Finance data={data}/>}
  {tab==='domain'&&<Domains data={data}/>}
  {tab==='legal'&&<Legal data={data}/>}
  <div className="supportGuard"><span>⚠</span><p><b>Support boundary:</b> this workspace is intentionally read-only. Future support overrides should require a selected tenant, reason, expiry and audit record.</p></div>
 </section>;
}

function Overview({data}){
 const o=data.outlet||{},b=data.billing;
 return <div className="tenant360Grid"><section className="card"><div className="cardHead"><div><span className="eyebrow">TENANT PROFILE</span><h2>At a glance</h2></div></div><div className="facts"><Field label="Status" value={o.status}/><Field label="Billing" value={o.billingPlan}/><Field label="Group" value={data.group?.name}/><Field label="Location" value={[o.city,o.state,o.pincode].filter(Boolean).join(', ')}/><Field label="Coverage" value={(o.deliveryCoverageMode||'Radius')+' · '+(o.serviceRadiusKm||0)+' km'}/><Field label="Staff" value={data.staffUsers}/></div></section><section className="card"><div className="cardHead"><div><span className="eyebrow">BILLING</span><h2>{b?.planName||'No plan'}</h2></div></div>{b?<div className="facts"><Field label="Cycle" value={b.billingCycle}/><Field label="Subscription" value={money(b.subscriptionFee)}/><Field label="Setup fee" value={money(b.setupFee)}/><Field label="Fee rate" value={b.transactionFeePercent+'%'}/><Field label="Renewal" value={formatDate(b.renewalDate)}/><Field label="Usage" value={b.activeCustomers+' / '+b.includedActiveCustomers}/><Field label="Status" value={b.status}/></div>:<Empty>No SaaS subscription is attached.</Empty>}</section></div>;
}
function Business({data}){const o=data.outlet||{},b=data.billing;return <div className="tenant360Grid"><section className="card"><div className="cardHead"><div><span className="eyebrow">BUSINESS</span><h2>Identity & location</h2></div></div><div className="facts"><Field label="Outlet" value={o.name}/><Field label="Slug" value={o.slug}/><Field label="Subdomain" value={o.subdomain}/><Field label="City" value={o.city}/><Field label="State" value={o.state}/><Field label="Pincode" value={o.pincode}/><Field label="Latitude" value={o.latitude?.toFixed?.(6)}/><Field label="Longitude" value={o.longitude?.toFixed?.(6)}/></div></section><section className="card"><div className="cardHead"><div><span className="eyebrow">COMMERCIAL</span><h2>Customer presentation</h2></div></div><div className="facts"><Field label="Package pricing" value={o.customPackagePricingMode}/><Field label="Show package" value={o.showPackagePriceToCustomer?'Yes':'No'}/><Field label="Show meal price" value={o.showMealPriceToCustomer?'Yes':'No'}/><Field label="Show delivery fee" value={o.showDeliveryFeeToCustomer?'Yes':'No'}/><Field label="SaaS plan" value={b?.planName}/><Field label="Renewal" value={formatDate(b?.renewalDate)}/></div></section></div>}
function Users({data}){const staff=data.staff||[];return <section className="card"><div className="cardHead"><div><span className="eyebrow">ACCESS</span><h2>Outlet staff</h2><p>{data.staffUsers||0} staff accounts across the tenant.</p></div></div><div className="miniEntityList">{staff.map(u=><div key={u.id}><span className="avatarCircle miniAvatar">{String(u.firstName||u.email||'U').charAt(0).toUpperCase()}</span><div><b>{[u.firstName,u.lastName].filter(Boolean).join(' ')||u.email}</b><small>{u.email} · {role(u.role)} · {u.isActive?'Active':'Disabled'}</small></div><Pill status={u.isActive?'Active':'Disabled'}/></div>)}{!staff.length&&<Empty>No outlet staff accounts found.</Empty>}</div></section>}
function Customers({data}){const rows=data.customers||[];return <section className="card"><div className="cardHead"><div><span className="eyebrow">CUSTOMERS</span><h2>Tenant customers</h2><p>{data.customerUsers||0} customer identities · {data.activeCustomers||0} active.</p></div><span className="countBadge">{rows.length} shown</span></div><div className="miniEntityList">{rows.map(u=><div key={u.id}><span className="avatarCircle miniAvatar">{String(u.firstName||u.email||'C').charAt(0).toUpperCase()}</span><div><b>{[u.firstName,u.lastName].filter(Boolean).join(' ')||u.email}</b><small>{u.email}{u.mobileNumber?' · '+u.mobileNumber:''}</small></div><Pill status={u.isActive?'Active':'Disabled'}/></div>)}{!rows.length&&<Empty>No customers found for this tenant.</Empty>}</div></section>}

function Kitchen({data}){return <div className="tenant360Grid"><section className="card"><div className="cardHead"><div><span className="eyebrow">CATALOG</span><h2>Kitchen catalogue</h2><p>Current production configuration visible to the support team.</p></div></div><div className="financeNumbers"><div><span>Meal plans</span><b>{data.mealPlanCount||0}</b><small>{data.activeMealPlanCount||0} active</small></div><div><span>Recipes</span><b>{data.recipeCount||0}</b><small>{data.activeRecipeCount||0} active</small></div><div><span>Menu items</span><b>{data.menuItemCount||0}</b><small>Outlet menu configuration</small></div><div><span>Today's deliveries</span><b>{data.deliveriesToday||0}</b><small>Current scheduled date</small></div></div></section><section className="card"><div className="cardHead"><div><span className="eyebrow">OPERATING PULSE</span><h2>Recent production activity</h2></div></div><div className="facts"><Field label="Deliveries · 30d" value={data.deliveries30Days}/><Field label="Orders · 30d" value={data.orders30Days}/><Field label="Subscriptions" value={data.totalSubscriptions}/><Field label="Active subscriptions" value={data.activeSubscriptions}/><Field label="Pending subscriptions" value={data.pendingSubscriptions}/><Field label="Cancelled subscriptions" value={data.cancelledSubscriptions}/></div></section></div>}

function Subscriptions({data}){const rows=data.recentSubscriptions||[];return <section className="card"><div className="cardHead"><div><span className="eyebrow">CUSTOMER REVENUE</span><h2>Recent subscriptions</h2><p>{data.totalSubscriptions||0} subscriptions in this tenant.</p></div></div><div className="compactDataTable"><div className="tableHead"><span>Plan</span><span>Customer</span><span>Status</span><span>Next delivery</span><span>Total</span></div>{rows.map(x=><div className="tableRow" key={x.id}><div><b>{x.planName}</b><small>{x.frequency} · {x.mealsPerWeek} meals/week</small></div><span className="mono">{x.customerId}</span><Pill status={x.status}/><span>{formatDate(x.nextDeliveryDate)}</span><b>{money(x.totalCharged)}</b></div>)}{!rows.length&&<Empty>No subscriptions found.</Empty>}</div></section>}
function Operations({data}){const deliveries=data.recentDeliveries||[],orders=data.recentOrders||[];return <div className="tenant360Bottom"><section className="card"><div className="cardHead"><div><span className="eyebrow">ORDERS</span><h2>Latest orders</h2></div></div><div className="miniEntityList">{orders.map(x=><div key={x.id}><span className="miniIcon">₹</span><div><b>{money(x.total)}</b><small>{formatDate(x.deliveryDate)} · {x.customerId}</small></div><Pill status={x.status}/></div>)}{!orders.length&&<Empty>No recent orders.</Empty>}</div></section><section className="card"><div className="cardHead"><div><span className="eyebrow">DELIVERIES</span><h2>Latest activity</h2></div></div><div className="miniEntityList">{deliveries.map(x=><div key={x.id}><span className="miniIcon">→</span><div><b>{x.customerName||'Customer'}</b><small>{formatDate(x.scheduledDate)} · {x.mealSlot}</small></div><Pill status={x.status}/></div>)}{!deliveries.length&&<Empty>No recent deliveries.</Empty>}</div></section></div>}
function Finance({data}){const t=data.taxSettings||{},b=data.billing;return <div className="tenant360Grid"><section className="card"><div className="cardHead"><div><span className="eyebrow">TENANT FINANCE</span><h2>30-day view</h2></div></div><div className="financeNumbers"><div><span>Transaction volume</span><b>{money(data.revenue30Days||0)}</b></div><div><span>Restaurant GST</span><b>{money(data.restaurantGst30Days||0)}</b></div><div><span>Platform fee</span><b>{money(data.platformFee30Days||0)}</b></div><div><span>Platform revenue</span><b>{money(data.platformRevenue30Days||0)}</b></div></div></section><section className="card"><div className="cardHead"><div><span className="eyebrow">TAX CONFIGURATION</span><h2>Restaurant GST</h2></div></div><div className="facts"><Field label="GST rate" value={(t.restaurantGstRate||0)+'%'}/><Field label="GST mode" value={t.restaurantGstMode}/><Field label="30d GST" value={money(data.restaurantGst30Days||0)}/><Field label="Platform fee" value={money(data.platformFee30Days||0)}/><Field label="SaaS plan" value={b?.planName}/></div></section></div>}
function Domains({data}){const rows=data.domains||[];return <section className="card"><div className="cardHead"><div><span className="eyebrow">TENANT ACCESS</span><h2>Domains</h2><p>Custom-domain lifecycle and platform-host access.</p></div></div><div className="domainList">{rows.map(x=><article className="domainCard" key={x.id}><div className="domainIdentity"><div className="domainIcon">◎</div><div><h3>{x.hostname}</h3><p>{x.type||'Custom'}{x.isPrimary?' · Primary':''}</p><small>Created {formatDate(x.createdAtUtc)}</small></div></div><Pill status={x.status}/></article>)}{!rows.length&&<Empty>No domains configured.</Empty>}</div></section>}
function Legal({data}){const o=data.outlet||{};return <section className="card"><div className="cardHead"><div><span className="eyebrow">LEGAL</span><h2>Outlet legal state</h2><p>Inspection only. Customer legal documents remain outlet-owned and versioned.</p></div></div><div className="facts"><Field label="Published" value={data.legalPoliciesPublished?'Yes':'No'}/><Field label="Current version" value={data.legalVersion}/><Field label="Effective date" value={formatDate(data.legalEffectiveDateUtc)}/></div><div className="legalBoundary"><b>Governance rule</b><span>Super Admin can inspect the tenant's legal state, but should not silently overwrite outlet customer Terms, Privacy or commercial policies.</span></div></section>}
